'use strict';

const crypto = require('crypto');
const { getDb } = require('../db');

class HardwareDeviceError extends Error {
  constructor(message, status = 400, code = 'HARDWARE_DEVICE_ERROR', details) { super(message); this.name = 'HardwareDeviceError'; this.status = status; this.code = code; this.details = details; }
}
const fail = (message, status, code, details) => new HardwareDeviceError(message, status, code, details);
const SAFE = /^[a-zA-Z0-9][a-zA-Z0-9_.:/@+ -]{0,299}$/; const SECRET = /password|secret|token|credential|private.?key|authorization|cookie/i;
const parse = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const canonical = value => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value;
const stable = value => JSON.stringify(canonical(value)); const hash = value => crypto.createHash('sha256').update(stable(value)).digest('hex');
const text = (value, key, max = 300) => { const result = String(value ?? '').trim(); if (!result || result.length > max || !SAFE.test(result)) throw fail(`${key} is invalid`); return result; };
const optional = (value, key, max = 300) => value == null || value === '' ? null : text(value, key, max);
const integer = (value, key, min = 0, max = Number.MAX_SAFE_INTEGER) => { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw fail(`${key} is invalid`); return result; };
const number = (value, key, min = 0, max = 1e15) => { const result = Number(value); if (!Number.isFinite(result) || result < min || result > max) throw fail(`${key} is invalid`); return result; };
const time = (value, key) => { const result = new Date(value); if (Number.isNaN(result.getTime())) throw fail(`${key} is invalid`); return result.toISOString(); };
const array = (value, key, max, mapper) => { if (value == null) return []; if (!Array.isArray(value) || value.length > max) throw fail(`${key} is invalid`); return value.map((item, index) => mapper(item, `${key}[${index}]`)); };
function safe(value) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw fail('inventory is invalid'); const encoded = stable(value); if (Buffer.byteLength(encoded) > 512 * 1024) throw fail('inventory is too large', 413); const walk = (node, path) => { if (!node || typeof node !== 'object') return; for (const [key, child] of Object.entries(node)) { if (SECRET.test(key)) throw fail(`${path}.${key} may not contain secrets`, 400, 'SECRET_FIELD'); walk(child, `${path}.${key}`); } }; walk(value, 'inventory'); }
function unique(items, key, field) { const seen = new Set(); for (const item of items) { if (seen.has(item[key])) throw fail(`${field} contains duplicate ${key}`); seen.add(item[key]); } }
function normalizeProfile(profile, key) { const total = integer(profile.total, `${key}.total`, 0, 100000); const available = integer(profile.available, `${key}.available`, 0, 100000); if (available > total) throw fail(`${key}.available cannot exceed total`); return { name: text(profile.name, `${key}.name`, 100), total, available, memoryBytes: integer(profile.memoryBytes, `${key}.memoryBytes`), licenseState: ['licensed','unlicensed','unknown'].includes(profile.licenseState) ? profile.licenseState : 'unknown' }; }
function normalizeMemoryTier(item, key) { const capacityBytes = integer(item.capacityBytes, `${key}.capacityBytes`); const usedBytes = integer(item.usedBytes ?? 0, `${key}.usedBytes`); if (usedBytes > capacityBytes) throw fail(`${key}.usedBytes cannot exceed capacityBytes`); return { kind: text(item.kind, `${key}.kind`, 40), capacityBytes, usedBytes, hitRatePercent: item.hitRatePercent == null ? null : number(item.hitRatePercent, `${key}.hitRatePercent`, 0, 100), workloadImpact: optional(item.workloadImpact, `${key}.workloadImpact`, 160) }; }

function normalize(body) {
  safe(body);
  const inventory = {
    memoryTiers: array(body.memoryTiers, 'memoryTiers', 64, normalizeMemoryTier),
    pciDevices: array(body.pciDevices, 'pciDevices', 4096, (item, key) => ({ id: text(item.id, `${key}.id`, 160), address: text(item.address, `${key}.address`, 40), vendor: text(item.vendor, `${key}.vendor`, 120), model: text(item.model, `${key}.model`, 180), classCode: text(item.classCode, `${key}.classCode`, 40), iommuGroup: integer(item.iommuGroup, `${key}.iommuGroup`, 0, 1048576), numaNode: item.numaNode == null ? null : integer(item.numaNode, `${key}.numaNode`, 0, 4095), resetSupported: Boolean(item.resetSupported), acsIsolated: Boolean(item.acsIsolated), kind: ['pci','pf','vf','gpu'].includes(item.kind) ? item.kind : 'pci', parentRef: optional(item.parentRef, `${key}.parentRef`, 160), driver: optional(item.driver, `${key}.driver`, 120), health: ['healthy','degraded','failed','unknown'].includes(item.health) ? item.health : 'unknown', allocatedTo: optional(item.allocatedTo, `${key}.allocatedTo`, 180) })),
    gpus: array(body.gpus, 'gpus', 1024, (item, key) => ({ id: text(item.id, `${key}.id`, 160), pciRef: text(item.pciRef, `${key}.pciRef`, 160), vendor: text(item.vendor, `${key}.vendor`, 120), model: text(item.model, `${key}.model`, 180), memoryBytes: integer(item.memoryBytes, `${key}.memoryBytes`), driverVersion: optional(item.driverVersion, `${key}.driverVersion`, 80), health: ['healthy','degraded','failed','unknown'].includes(item.health) ? item.health : 'unknown', migCapable: Boolean(item.migCapable), profiles: array(item.profiles, `${key}.profiles`, 128, normalizeProfile) })),
    usbDevices: array(body.usbDevices, 'usbDevices', 2048, (item, key) => ({ id: text(item.id, `${key}.id`, 160), vendorId: text(item.vendorId, `${key}.vendorId`, 20), productId: text(item.productId, `${key}.productId`, 20), vendor: text(item.vendor, `${key}.vendor`, 120), model: text(item.model, `${key}.model`, 180), busPath: text(item.busPath, `${key}.busPath`, 160), owner: optional(item.owner, `${key}.owner`, 160), mappedTo: optional(item.mappedTo, `${key}.mappedTo`, 180), mobility: ['host-bound','remappable','unknown'].includes(item.mobility) ? item.mobility : 'unknown' })),
  };
  unique(inventory.pciDevices, 'id', 'pciDevices'); unique(inventory.pciDevices, 'address', 'pciDevices'); unique(inventory.gpus, 'id', 'gpus'); unique(inventory.usbDevices, 'id', 'usbDevices');
  const pciRefs = new Set(inventory.pciDevices.map(item => item.id));
  for (const gpu of inventory.gpus) { unique(gpu.profiles, 'name', `gpu ${gpu.id} profiles`); if (!pciRefs.has(gpu.pciRef)) throw fail(`GPU ${gpu.id} references an unknown PCI device`); }
  for (const device of inventory.pciDevices.filter(item => item.kind === 'vf')) if (!device.parentRef || !pciRefs.has(device.parentRef)) throw fail(`VF ${device.id} references an unknown PF`);
  return inventory;
}

class HardwareDeviceService {
  constructor(dbProvider = getDb) { this._dbProvider = dbProvider; }
  _db() { return this._dbProvider(); } _admin(actor) { if (!actor?.id) throw fail('Authentication required', 401); if (actor.role !== 'admin') throw fail('Administrator required', 403); }
  _latest(hostId = null) { const rows = this._db().prepare(`SELECT s.* FROM hardware_device_snapshots s WHERE NOT EXISTS (SELECT 1 FROM hardware_device_snapshots n WHERE n.host_id=s.host_id AND (datetime(n.observed_at)>datetime(s.observed_at) OR (n.observed_at=s.observed_at AND n.id>s.id))) ${hostId ? 'AND s.host_id=?' : ''} ORDER BY s.host_id`).all(...(hostId ? [integer(hostId, 'hostId', 1)] : [])); return rows.map(row => ({ id: row.id, hostId: row.host_id, observedAt: row.observed_at, inventory: parse(row.inventory_json, {}), evidenceHash: row.evidence_hash })); }
  _snapshot(hostId) { const item = this._latest(hostId)[0]; if (!item) throw fail('Device snapshot not found', 404); return item; }
  record(body, actor) { this._admin(actor); const hostId = integer(body.hostId, 'hostId', 1); if (!this._db().prepare('SELECT 1 FROM docker_hosts WHERE id=?').get(hostId)) throw fail('Host not found', 404); const observedAt = time(body.observedAt || new Date(), 'observedAt'); const inventory = normalize(body); const evidenceHash = hash({ hostId, observedAt, inventory }); const found = this._db().prepare('SELECT * FROM hardware_device_snapshots WHERE evidence_hash=?').get(evidenceHash); if (found) return { id: found.id, hostId, observedAt, inventory, evidenceHash, duplicate: true }; const saved = this._db().prepare('INSERT INTO hardware_device_snapshots (host_id,observed_at,inventory_json,evidence_hash,created_by) VALUES (?,?,?,?,?)').run(hostId, observedAt, stable(inventory), evidenceHash, actor.id); return { id: Number(saved.lastInsertRowid), hostId, observedAt, inventory, evidenceHash, duplicate: false }; }
  memoryTiers(hostId, actor) { this._admin(actor); const snapshot = this._snapshot(hostId); return { hostId: snapshot.hostId, tiers: snapshot.inventory.memoryTiers.map(tier => ({ ...tier, utilizationRatio: tier.capacityBytes ? Number((tier.usedBytes / tier.capacityBytes).toFixed(4)) : null })), evidenceHash: snapshot.evidenceHash }; }
  pci(hostId, actor) { this._admin(actor); const snapshot = this._snapshot(hostId); const groups = new Map(); for (const item of snapshot.inventory.pciDevices) groups.set(item.iommuGroup, [...(groups.get(item.iommuGroup) || []), item]); return { hostId: snapshot.hostId, devices: snapshot.inventory.pciDevices.map(item => ({ ...item, passthroughReady: item.health === 'healthy' && item.resetSupported && item.acsIsolated && !item.allocatedTo, blockers: [item.health !== 'healthy' && 'health', !item.resetSupported && 'reset', !item.acsIsolated && 'iommu_isolation', item.allocatedTo && 'allocated'].filter(Boolean) })), iommuGroups: [...groups.entries()].map(([group, devices]) => ({ group, deviceRefs: devices.map(item => item.id), isolated: devices.every(item => item.acsIsolated) })), evidenceHash: snapshot.evidenceHash }; }
  gpus(hostId, actor) { this._admin(actor); const snapshot = this._snapshot(hostId); return { hostId: snapshot.hostId, devices: snapshot.inventory.gpus, evidenceHash: snapshot.evidenceHash }; }
  usb(hostId, actor) { this._admin(actor); const snapshot = this._snapshot(hostId); return { hostId: snapshot.hostId, devices: snapshot.inventory.usbDevices.map(item => ({ ...item, caveats: [item.mobility === 'host-bound' ? 'migration requires remapping' : null, item.mappedTo ? 'already mapped' : null, !item.owner ? 'owner missing' : null].filter(Boolean) })), evidenceHash: snapshot.evidenceHash }; }
  planAllocation(body, actor) { this._admin(actor); const hostId = integer(body.hostId, 'hostId', 1); const snapshot = this._snapshot(hostId); const kind = String(body.kind || 'pci'); if (!['pci','sriov_vf','gpu','vgpu'].includes(kind)) throw fail('kind is invalid'); let deviceRef = optional(body.deviceRef, 'deviceRef', 160); const profileName = optional(body.profileName, 'profileName', 100); if (kind === 'vgpu' && !profileName) throw fail('profileName is required for vGPU'); if (kind !== 'vgpu' && profileName) throw fail('profileName is only valid for vGPU'); const target = text(body.targetResourceKey, 'targetResourceKey', 180); const tenantId = body.tenantId == null ? null : integer(body.tenantId, 'tenantId', 1); if (tenantId && !this._db().prepare('SELECT 1 FROM tenants WHERE id=?').get(tenantId)) throw fail('Tenant not found', 404); let device; let profile;
    if (kind === 'sriov_vf') { const planned = new Set(this._db().prepare("SELECT device_ref FROM hardware_device_allocations WHERE host_id=? AND device_kind='sriov_vf' AND state='planned'").all(hostId).map(item => item.device_ref)); const candidates = snapshot.inventory.pciDevices.filter(item => item.kind === 'vf' && (!body.parentRef || item.parentRef === body.parentRef) && !item.allocatedTo && !planned.has(item.id)); device = deviceRef ? candidates.find(item => item.id === deviceRef) : candidates[0]; deviceRef = device?.id; }
    else if (kind === 'gpu' || kind === 'vgpu') { const gpu = snapshot.inventory.gpus.find(item => item.id === deviceRef); device = snapshot.inventory.pciDevices.find(item => item.id === gpu?.pciRef); if (kind === 'vgpu') profile = gpu?.profiles.find(item => item.name === profileName); }
    else device = snapshot.inventory.pciDevices.find(item => item.id === deviceRef);
    if (!deviceRef || !device) throw fail('Eligible device not found', 404, 'DEVICE_NOT_FOUND'); const blockers = [];
    if (device.health !== 'healthy') blockers.push('device health is not healthy'); if (device.allocatedTo) blockers.push('provider reports an existing allocation'); if (!device.resetSupported) blockers.push('function-level reset unsupported'); if (!device.acsIsolated) blockers.push('IOMMU group is not isolated'); if (kind === 'vgpu' && (!profile || profile.available < 1 || profile.licenseState !== 'licensed')) blockers.push('vGPU profile capacity/license unavailable');
    const planned = this._db().prepare("SELECT device_kind,profile_name FROM hardware_device_allocations WHERE host_id=? AND device_ref=? AND state='planned'").all(hostId, deviceRef);
    if (kind === 'gpu' && planned.length) blockers.push('control-plane allocation already planned');
    else if (kind === 'vgpu') { const used = planned.filter(item => item.device_kind === 'vgpu' && item.profile_name === profileName).length; if (planned.some(item => item.device_kind === 'gpu')) blockers.push('full GPU allocation already planned'); if (profile && used >= profile.available) blockers.push('vGPU profile capacity already planned'); }
    else if (planned.length) blockers.push('control-plane allocation already planned');
    const constraints = { numaNode: device.numaNode, migration: 'blocked until an equivalent target mapping is proven', ha: 'restart requires equivalent device capacity', blockers };
    const plan = { hostId, kind, deviceRef, profileName, targetResourceKey: target, tenantId, constraints, applyEndpoint: null, providerMutationsStarted: 0 };
    if (blockers.length) return { state: 'blocked', plan, planHash: hash(plan), blockers, providerMutationsStarted: 0 };
    const planHash = hash(plan); const saved = this._db().prepare(`INSERT INTO hardware_device_allocations (host_id,device_kind,device_ref,profile_name,target_resource_key,tenant_id,constraints_json,plan_json,plan_hash,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(hostId, kind, deviceRef, profileName, target, tenantId, stable(constraints), stable(plan), planHash, actor.id); return { id: Number(saved.lastInsertRowid), state: 'planned', plan, planHash, blockers: [], providerMutationsStarted: 0 };
  }
  releaseAllocation(id, actor) { this._admin(actor); const result = this._db().prepare("UPDATE hardware_device_allocations SET state='released',released_at=datetime('now') WHERE id=? AND state='planned'").run(integer(id, 'id', 1)); if (!result.changes) throw fail('Planned allocation not found', 404); return { released: true, infrastructureMutated: false }; }
  recordMetrics(body, actor) { this._admin(actor); const hostId = integer(body.hostId, 'hostId', 1); const snapshot = this._snapshot(hostId); const deviceRef = text(body.deviceRef, 'deviceRef', 160); if (!snapshot.inventory.gpus.some(item => item.id === deviceRef)) throw fail('GPU not found in latest snapshot', 404, 'DEVICE_NOT_FOUND'); const metrics = { smPercent: number(body.smPercent ?? 0, 'smPercent', 0, 100), memoryPercent: number(body.memoryPercent ?? 0, 'memoryPercent', 0, 100), encoderPercent: number(body.encoderPercent ?? 0, 'encoderPercent', 0, 100), eccErrors: integer(body.eccErrors ?? 0, 'eccErrors'), throttleReasons: array(body.throttleReasons, 'throttleReasons', 32, (item, key) => text(item, key, 80)) }; const observedAt = time(body.observedAt || new Date(), 'observedAt'); const resourceKey = optional(body.resourceKey, 'resourceKey', 180); const evidenceHash = hash({ hostId, deviceRef, resourceKey, observedAt, metrics }); const found = this._db().prepare('SELECT id FROM hardware_accelerator_metrics WHERE evidence_hash=?').get(evidenceHash); if (found) return { id: found.id, duplicate: true, metrics, evidenceHash }; const saved = this._db().prepare('INSERT INTO hardware_accelerator_metrics (host_id,device_ref,resource_key,observed_at,metrics_json,evidence_hash,created_by) VALUES (?,?,?,?,?,?,?)').run(hostId, deviceRef, resourceKey, observedAt, stable(metrics), evidenceHash, actor.id); return { id: Number(saved.lastInsertRowid), duplicate: false, metrics, evidenceHash }; }
  reserve(body, actor) { this._admin(actor); const hostId = integer(body.hostId, 'hostId', 1); const deviceRef = text(body.deviceRef, 'deviceRef', 160); const profileName = optional(body.profileName, 'profileName', 100); const gpu = this._snapshot(hostId).inventory.gpus.find(item => item.id === deviceRef); if (!gpu) throw fail('GPU not found in latest snapshot', 404, 'DEVICE_NOT_FOUND'); if (profileName && !gpu.profiles.some(item => item.name === profileName && item.licenseState === 'licensed')) throw fail('Licensed GPU profile not found', 404, 'PROFILE_NOT_FOUND'); const tenantId = integer(body.tenantId, 'tenantId', 1); if (!this._db().prepare('SELECT 1 FROM tenants WHERE id=?').get(tenantId)) throw fail('Tenant not found', 404); const startsAt = time(body.startsAt, 'startsAt'); const endsAt = time(body.endsAt, 'endsAt'); if (new Date(endsAt) <= new Date(startsAt)) throw fail('endsAt must be after startsAt'); const purpose = text(body.purpose, 'purpose', 300); const reservationHash = hash({ hostId, deviceRef, profileName, tenantId, startsAt, endsAt, purpose }); const duplicate = this._db().prepare('SELECT id FROM hardware_accelerator_reservations WHERE reservation_hash=?').get(reservationHash); if (duplicate) return { id: duplicate.id, hostId, deviceRef, profileName, tenantId, startsAt, endsAt, purpose, state: 'reserved', reservationHash, duplicate: true, providerMutationsStarted: 0 }; this._expireReservations(); const overlap = this._db().prepare("SELECT id FROM hardware_accelerator_reservations WHERE host_id=? AND device_ref=? AND (profile_name IS NULL OR ? IS NULL OR profile_name=?) AND state='reserved' AND datetime(starts_at)<datetime(?) AND datetime(ends_at)>datetime(?)").get(hostId, deviceRef, profileName, profileName, endsAt, startsAt); if (overlap) throw fail('Reservation overlaps an active window', 409, 'RESERVATION_CONFLICT'); const saved = this._db().prepare('INSERT INTO hardware_accelerator_reservations (host_id,device_ref,profile_name,tenant_id,starts_at,ends_at,purpose,reservation_hash,created_by) VALUES (?,?,?,?,?,?,?,?,?)').run(hostId, deviceRef, profileName, tenantId, startsAt, endsAt, purpose, reservationHash, actor.id); return { id: Number(saved.lastInsertRowid), hostId, deviceRef, profileName, tenantId, startsAt, endsAt, purpose, state: 'reserved', reservationHash, duplicate: false, providerMutationsStarted: 0 }; }
  _expireReservations() { this._db().prepare("UPDATE hardware_accelerator_reservations SET state='expired' WHERE state='reserved' AND datetime(ends_at)<=datetime('now')").run(); }
  overview(actor) { this._admin(actor); this._expireReservations(); const snapshots = this._latest(); const allocations = this._db().prepare("SELECT * FROM hardware_device_allocations ORDER BY id DESC LIMIT 500").all().map(row => ({ id: row.id, hostId: row.host_id, kind: row.device_kind, deviceRef: row.device_ref, profileName: row.profile_name, targetResourceKey: row.target_resource_key, state: row.state, planHash: row.plan_hash, providerMutationsStarted: 0 })); const metrics = this._db().prepare('SELECT * FROM hardware_accelerator_metrics ORDER BY datetime(observed_at) DESC,id DESC LIMIT 200').all().map(row => ({ id: row.id, hostId: row.host_id, deviceRef: row.device_ref, resourceKey: row.resource_key, observedAt: row.observed_at, metrics: parse(row.metrics_json, {}), evidenceHash: row.evidence_hash })); const reservations = this._db().prepare("SELECT * FROM hardware_accelerator_reservations WHERE state='reserved' ORDER BY datetime(starts_at)").all().map(row => ({ id: row.id, hostId: row.host_id, deviceRef: row.device_ref, profileName: row.profile_name, tenantId: row.tenant_id, startsAt: row.starts_at, endsAt: row.ends_at, purpose: row.purpose, state: row.state, providerMutationsStarted: 0 })); return { capabilities: { memoryTiering: true, pciInventory: true, pciPassthroughPlan: true, sriovVfAllocator: true, gpuInventory: true, gpuPassthroughPlan: true, vgpuProfileAllocator: true, gpuMetrics: true, acceleratorReservations: true, usbInventory: true }, safety: { providerMutationsStarted: 0, applyEndpoint: false }, snapshots, allocations, metrics, reservations }; }
}

const service = new HardwareDeviceService(); module.exports = service; module.exports.HardwareDeviceService = HardwareDeviceService; module.exports.HardwareDeviceError = HardwareDeviceError;
