'use strict';

const crypto = require('crypto');
const os = require('os');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { getDb } = require('../db');

const execFileAsync = promisify(execFile);
class MigrationFactoryError extends Error {
  constructor(message, status = 400, code = 'MIGRATION_FACTORY_ERROR', details) { super(message); this.name = 'MigrationFactoryError'; this.status = status; this.code = code; this.details = details; }
}
const fail = (message, status, code, details) => new MigrationFactoryError(message, status, code, details);
const FIELD = /^[a-zA-Z][a-zA-Z0-9_.:/@+-]{0,159}$/; const HASH = /^[a-f0-9]{64}$/; const CIDR = /^[0-9a-fA-F:.]+\/\d{1,3}$/;
const FORBIDDEN = /password|credential|private.?key|authorization|cookie|secret.?value|raw.?secret/i;
const FORMATS = new Set(['vmdk','vhdx','qcow2','raw','vhd','ova']);
const SANDBOX_POLICY = Object.freeze({ processBoundary: 'node-child-process', worker: 'fixed-conversion-contract-validator', conversionBinaryExecuted: false,
  inputPathsExposed: false, network: 'none', environment: 'empty', memoryLimitMb: 32, timeoutMs: 2000, maxResponseBytes: 16384 });
const WORKER = `'use strict';const input=JSON.parse(Buffer.from(process.argv[1],'base64url').toString('utf8'));const formats=new Set(['vmdk','vhdx','qcow2','raw','vhd','ova']);if(!formats.has(input.inputFormat)||!formats.has(input.outputFormat))process.exit(23);const tool=input.normalizeGuest?'virt-v2v':'qemu-img';process.stdout.write(JSON.stringify({requestHash:input.requestHash,tool,inputFormat:input.inputFormat,outputFormat:input.outputFormat,inputChecksumSha256:input.inputChecksumSha256,expectedOutputChecksumSha256:input.expectedOutputChecksumSha256,workerPid:process.pid,conversionExecuted:false}));`;
const canonical = value => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value;
const stable = value => JSON.stringify(canonical(value)); const hash = value => crypto.createHash('sha256').update(stable(value)).digest('hex');
const string = (value, field, max = 300) => { const result = String(value ?? '').trim(); if (!result || result.length > max || /[\u0000-\u001f\u007f]/.test(result)) throw fail(`${field} is invalid`); return result; };
const key = (value, field) => { const result = string(value, field, 160); if (!FIELD.test(result)) throw fail(`${field} is invalid`); return result; };
const integer = (value, field, min = 0, max = Number.MAX_SAFE_INTEGER) => { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw fail(`${field} is invalid`); return result; };
const choice = (value, field, values) => { const result = String(value || ''); if (!values.includes(result)) throw fail(`${field} is invalid`); return result; };
function exact(value, field, allowed) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw fail(`${field} is invalid`); const unexpected = Object.keys(value).filter(item => !allowed.includes(item)); if (unexpected.length) { const secret = unexpected.find(item => FORBIDDEN.test(item)); throw fail(secret ? `${field}.${secret} may not contain secret material` : `Unexpected ${field} fields: ${unexpected.join(', ')}`, 400, secret ? 'SECRET_FIELD' : 'UNEXPECTED_FIELD'); } return value; }
function safeObject(value, field, maxBytes = 128 * 1024) { if (!value || typeof value !== 'object' || Array.isArray(value) || Buffer.byteLength(stable(value)) > maxBytes) throw fail(`${field} is invalid`); const walk = (node, path) => { if (!node || typeof node !== 'object') return; for (const [childKey, child] of Object.entries(node)) { if (FORBIDDEN.test(childKey)) throw fail(`${path}.${childKey} may not contain secret material`, 400, 'SECRET_FIELD'); walk(child, `${path}.${childKey}`); } }; walk(value, field); return canonical(value); }
function checksum(value, field) { const result = String(value || '').toLowerCase(); if (!HASH.test(result)) throw fail(`${field} is invalid`); return result; }

class MigrationFactoryService {
  constructor(dbProvider = getDb) { this._dbProvider = dbProvider; }
  _db() { return this._dbProvider(); }
  _admin(actor) { if (!actor?.id) throw fail('Authentication required', 401); if (actor.role !== 'admin') throw fail('Administrator required', 403); }
  _row(table, idValue, label) { const id = integer(idValue, `${label}Id`, 1); const row = this._db().prepare(`SELECT * FROM ${table} WHERE id=?`).get(id); if (!row) throw fail(`${label} not found`, 404); return row; }
  assess(body, actor) {
    this._admin(actor); exact(body, 'assessment', ['sourceProvider','targetProvider','sourceInventory','dependencies','targetCandidates']); const sourceProvider = key(body.sourceProvider, 'sourceProvider').toLowerCase(); const targetProvider = key(body.targetProvider, 'targetProvider').toLowerCase(); const inventory = safeObject(body.sourceInventory, 'sourceInventory', 512 * 1024); if (!Array.isArray(inventory.vms) || inventory.vms.length > 5000) throw fail('sourceInventory.vms is invalid'); const normalizedVms = inventory.vms.map((vm, index) => { exact(vm, `vms[${index}]`, ['resourceKey','name','cpu','memoryBytes','diskBytes','networks','diskFormats','devices','os']); return { resourceKey: key(vm.resourceKey, `vms[${index}].resourceKey`), name: string(vm.name, `vms[${index}].name`, 200), cpu: integer(vm.cpu, `vms[${index}].cpu`, 1, 1024), memoryBytes: integer(vm.memoryBytes, `vms[${index}].memoryBytes`, 1), diskBytes: integer(vm.diskBytes, `vms[${index}].diskBytes`, 0), networks: Array.isArray(vm.networks) ? vm.networks.map(item => key(item, 'network')) : [], diskFormats: Array.isArray(vm.diskFormats) ? vm.diskFormats.map(item => choice(item, 'diskFormat', [...FORMATS])) : [], devices: Array.isArray(vm.devices) ? vm.devices.map(item => key(item, 'device')) : [], os: string(vm.os, `vms[${index}].os`, 120) }; }); const resourceKeys = new Set(normalizedVms.map(vm => vm.resourceKey)); if (resourceKeys.size !== normalizedVms.length) throw fail('VM resource keys must be unique');
    if (!Array.isArray(body.dependencies) || body.dependencies.length > 20000) throw fail('dependencies is invalid'); const dependencies = body.dependencies.map((edge, index) => { exact(edge, `dependencies[${index}]`, ['from','to','kind']); const from = key(edge.from, 'dependency.from'); const to = key(edge.to, 'dependency.to'); if (!resourceKeys.has(from) || !resourceKeys.has(to) || from === to) throw fail('Dependency endpoints are invalid'); return { from, to, kind: choice(edge.kind, 'dependency.kind', ['application','network','storage','startup','data']) }; });
    if (!Array.isArray(body.targetCandidates) || !body.targetCandidates.length || body.targetCandidates.length > 100) throw fail('targetCandidates is invalid'); const candidates = body.targetCandidates.map((candidate, index) => { exact(candidate, `targetCandidates[${index}]`, ['targetRef','capacityScore','compatibilityScore','networkScore','storageScore','blockers']); const blockers = Array.isArray(candidate.blockers) ? candidate.blockers.map(item => string(item, 'candidate blocker', 300)) : []; const scores = ['capacityScore','compatibilityScore','networkScore','storageScore'].map(field => integer(candidate[field], field, 0, 100)); return { targetRef: key(candidate.targetRef, 'targetRef'), capacityScore: scores[0], compatibilityScore: scores[1], networkScore: scores[2], storageScore: scores[3], score: Number((scores.reduce((sum, value) => sum + value, 0) / 4).toFixed(2)), blockers }; }).sort((a, b) => b.score - a.score); const blockers = []; for (const vm of normalizedVms) { if (!vm.diskFormats.length) blockers.push(`${vm.resourceKey}:disk_format_missing`); if (vm.devices.some(item => /pci|gpu|sriov/i.test(item))) blockers.push(`${vm.resourceKey}:passthrough_device_review`); } if (!candidates.some(item => !item.blockers.length)) blockers.push('no_unblocked_target_candidate'); const normalizedInventory = { ...inventory, vms: normalizedVms }; const state = blockers.length ? 'blocked' : 'ready'; const assessment = { sourceProvider, targetProvider, inventory: normalizedInventory, dependencies, blockers, candidates, state }; const assessmentHash = hash(assessment); const found = this._db().prepare('SELECT id FROM migration_factory_assessments WHERE assessment_hash=?').get(assessmentHash); const id = found?.id || Number(this._db().prepare('INSERT INTO migration_factory_assessments (source_provider,target_provider,inventory_json,inventory_hash,dependencies_json,blockers_json,candidates_json,state,assessment_hash,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)').run(sourceProvider, targetProvider, stable(normalizedInventory), hash(normalizedInventory), stable(dependencies), stable(blockers), stable(candidates), state, assessmentHash, actor.id).lastInsertRowid); return { id, ...assessment, assessmentHash, duplicate: Boolean(found), providerMutationsStarted: 0 };
  }
  async planConversion(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'conversion', ['inputFormat','outputFormat','inputChecksumSha256','expectedOutputChecksumSha256','normalizeGuest']); const inputFormat = choice(body.inputFormat, 'inputFormat', [...FORMATS]); const outputFormat = choice(body.outputFormat, 'outputFormat', [...FORMATS]); if (inputFormat === outputFormat && body.normalizeGuest !== true) throw fail('Conversion must change format or normalize the guest'); const inputChecksumSha256 = checksum(body.inputChecksumSha256, 'inputChecksumSha256'); const expectedOutputChecksumSha256 = checksum(body.expectedOutputChecksumSha256, 'expectedOutputChecksumSha256'); const request = { assessmentId: assessment.id, inputFormat, outputFormat, inputChecksumSha256, expectedOutputChecksumSha256, normalizeGuest: body.normalizeGuest === true }; const requestHash = hash(request); request.requestHash = requestHash; let result; try { const output = await execFileAsync(process.execPath, [`--max-old-space-size=${SANDBOX_POLICY.memoryLimitMb}`, '-e', WORKER, Buffer.from(JSON.stringify(request)).toString('base64url')], { cwd: os.tmpdir(), env: {}, timeout: SANDBOX_POLICY.timeoutMs, maxBuffer: SANDBOX_POLICY.maxResponseBytes, windowsHide: true }); result = JSON.parse(output.stdout); } catch (error) { throw fail('Conversion contract worker failed', 502, 'CONVERSION_WORKER_FAILED', String(error.message || error.code)); } if (result.requestHash !== requestHash) throw fail('Conversion worker response mismatch', 502, 'WORKER_RESPONSE_MISMATCH'); result.outOfProcess = result.workerPid !== process.pid; delete result.workerPid; const saved = this._db().prepare('INSERT OR IGNORE INTO migration_conversion_jobs (assessment_id,input_format,output_format,tool,input_checksum_sha256,expected_output_checksum_sha256,request_hash,sandbox_policy_json,worker_response_json,out_of_process,created_by) VALUES (?,?,?,?,?,?,?,?,?,1,?)').run(assessment.id, inputFormat, outputFormat, result.tool, inputChecksumSha256, expectedOutputChecksumSha256, requestHash, stable(SANDBOX_POLICY), stable(result), actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, ...result, requestHash, state: 'planned', sandboxPolicy: SANDBOX_POLICY, diskIoStarted: 0 };
  }
  mapNetworks(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'networkMapping', ['mappings']); if (!Array.isArray(body.mappings) || !body.mappings.length || body.mappings.length > 1000) throw fail('mappings is invalid'); const seen = new Set(); const conflicts = []; const mappings = body.mappings.map((item, index) => { exact(item, `mappings[${index}]`, ['sourceNetwork','targetNetwork','sourceVlan','targetVlan','sourceCidr','targetCidr','securityProfile','ipMode']); const sourceNetwork = key(item.sourceNetwork, 'sourceNetwork'); if (seen.has(sourceNetwork)) conflicts.push(`${sourceNetwork}:duplicate_mapping`); seen.add(sourceNetwork); const sourceCidr = string(item.sourceCidr, 'sourceCidr', 80); const targetCidr = string(item.targetCidr, 'targetCidr', 80); if (!CIDR.test(sourceCidr) || !CIDR.test(targetCidr)) throw fail('CIDR mapping is invalid'); const ipMode = choice(item.ipMode, 'ipMode', ['preserve','reallocate']); if (ipMode === 'preserve' && sourceCidr !== targetCidr) conflicts.push(`${sourceNetwork}:preserve_ip_cidr_mismatch`); return { sourceNetwork, targetNetwork: key(item.targetNetwork, 'targetNetwork'), sourceVlan: integer(item.sourceVlan, 'sourceVlan', 0, 4094), targetVlan: integer(item.targetVlan, 'targetVlan', 0, 4094), sourceCidr, targetCidr, securityProfile: key(item.securityProfile, 'securityProfile'), ipMode }; }); const state = conflicts.length ? 'blocked' : 'ready'; const planHash = hash({ assessmentHash: assessment.assessment_hash, mappings, conflicts }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_network_mappings (assessment_id,mappings_json,conflicts_json,state,plan_hash,created_by) VALUES (?,?,?,?,?,?)').run(assessment.id, stable(mappings), stable(conflicts), state, planHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, mappings, conflicts, state, planHash, providerMutationsStarted: 0 };
  }
  mapStorage(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'storageMapping', ['mappings']); if (!Array.isArray(body.mappings) || !body.mappings.length || body.mappings.length > 5000) throw fail('mappings is invalid'); const blockers = []; const reservations = {}; const mappings = body.mappings.map((item, index) => { exact(item, `mappings[${index}]`, ['diskRef','sizeBytes','targetDatastore','targetPolicy','targetTier','availableBytes','thinProvisioned']); const diskRef = key(item.diskRef, 'diskRef'); const sizeBytes = integer(item.sizeBytes, 'sizeBytes', 1); const availableBytes = integer(item.availableBytes, 'availableBytes', 0); const targetDatastore = key(item.targetDatastore, 'targetDatastore'); reservations[targetDatastore] = (reservations[targetDatastore] || 0) + sizeBytes; if (reservations[targetDatastore] > availableBytes) blockers.push(`${diskRef}:insufficient_capacity`); return { diskRef, sizeBytes, targetDatastore, targetPolicy: key(item.targetPolicy, 'targetPolicy'), targetTier: key(item.targetTier, 'targetTier'), availableBytes, thinProvisioned: item.thinProvisioned === true }; }); const reservationList = Object.entries(reservations).map(([targetDatastore, bytes]) => ({ targetDatastore, bytes })); const state = blockers.length ? 'blocked' : 'ready'; const planHash = hash({ assessmentHash: assessment.assessment_hash, mappings, reservationList, blockers }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_storage_mappings (assessment_id,mappings_json,reservations_json,blockers_json,state,plan_hash,created_by) VALUES (?,?,?,?,?,?,?)').run(assessment.id, stable(mappings), stable(reservationList), stable(blockers), state, planHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, mappings, reservations: reservationList, blockers, state, planHash, providerMutationsStarted: 0 };
  }
  recordTestClone(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'testClone', ['networkMappingId','storageMappingId','targetRef','isolationMode','checks']); const networkMapping = this._row('migration_network_mappings', body.networkMappingId, 'Network mapping'); const storageMapping = this._row('migration_storage_mappings', body.storageMappingId, 'Storage mapping'); if (networkMapping.assessment_id !== assessment.id || storageMapping.assessment_id !== assessment.id) throw fail('Mappings belong to another assessment', 409); const isolationMode = choice(body.isolationMode, 'isolationMode', ['isolated','no_uplink','sandbox']); if (!Array.isArray(body.checks) || !body.checks.length || body.checks.length > 100) throw fail('checks is invalid'); const checks = body.checks.map((item, index) => { exact(item, `checks[${index}]`, ['name','state','evidenceHash']); return { name: key(item.name, 'check.name'), state: choice(item.state, 'check.state', ['pass','fail']), evidenceHash: checksum(item.evidenceHash, 'check.evidenceHash') }; }); const state = assessment.state === 'ready' && networkMapping.state === 'ready' && storageMapping.state === 'ready' && checks.every(item => item.state === 'pass') ? 'validated' : 'blocked'; const evidenceHash = hash({ assessmentHash: assessment.assessment_hash, networkPlanHash: networkMapping.plan_hash, storagePlanHash: storageMapping.plan_hash, targetRef: body.targetRef, isolationMode, checks, state }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_test_clones (assessment_id,network_mapping_id,storage_mapping_id,target_ref,isolation_mode,checks_json,evidence_hash,state,created_by) VALUES (?,?,?,?,?,?,?,?,?)').run(assessment.id, networkMapping.id, storageMapping.id, key(body.targetRef, 'targetRef'), isolationMode, stable(checks), evidenceHash, state, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, targetRef: body.targetRef, isolationMode, checks, state, evidenceHash, externalExecutionAttested: true, sourceCutoverStarted: 0, providerMutationsStarted: 0 };
  }
  planWaves(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'wavePlan', ['workloads','maxConcurrent']); const maxConcurrent = integer(body.maxConcurrent, 'maxConcurrent', 1, 100); if (!Array.isArray(body.workloads) || !body.workloads.length || body.workloads.length > 5000) throw fail('workloads is invalid'); const workloads = body.workloads.map((item, index) => { exact(item, `workloads[${index}]`, ['resourceKey','application','dependencies','downtimeMinutes','windowRef']); return { resourceKey: key(item.resourceKey, 'resourceKey'), application: key(item.application, 'application'), dependencies: Array.isArray(item.dependencies) ? item.dependencies.map(dep => key(dep, 'dependency')) : [], downtimeMinutes: integer(item.downtimeMinutes, 'downtimeMinutes', 0, 10080), windowRef: key(item.windowRef, 'windowRef') }; }); const byKey = new Map(workloads.map(item => [item.resourceKey, item])); const blockers = []; if (byKey.size !== workloads.length) blockers.push('duplicate_workload'); for (const item of workloads) for (const dep of item.dependencies) if (!byKey.has(dep)) blockers.push(`${item.resourceKey}:missing_dependency:${dep}`); const remaining = new Set(byKey.keys()); const waves = []; while (remaining.size && !blockers.length) { const ready = [...remaining].filter(resourceKey => byKey.get(resourceKey).dependencies.every(dep => !remaining.has(dep))).sort().slice(0, maxConcurrent); if (!ready.length) { blockers.push('dependency_cycle'); break; } waves.push({ number: waves.length + 1, workloads: ready, applications: [...new Set(ready.map(item => byKey.get(item).application))], windows: [...new Set(ready.map(item => byKey.get(item).windowRef))], estimatedDowntimeMinutes: Math.max(...ready.map(item => byKey.get(item).downtimeMinutes)) }); ready.forEach(item => remaining.delete(item)); } const state = assessment.state === 'ready' && !blockers.length ? 'ready' : 'blocked'; const planHash = hash({ assessmentHash: assessment.assessment_hash, maxConcurrent, workloads, waves, blockers }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_wave_plans (assessment_id,max_concurrent,waves_json,blockers_json,state,plan_hash,created_by) VALUES (?,?,?,?,?,?,?)').run(assessment.id, maxConcurrent, stable(waves), stable(blockers), state, planHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, maxConcurrent, waves, blockers, state, planHash };
  }
  planCutover(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'cutover', ['wavePlanId','testCloneId','targetRef','approvalHash','confirmation']); const wave = this._row('migration_wave_plans', body.wavePlanId, 'Wave plan'); const clone = this._row('migration_test_clones', body.testCloneId, 'Test clone'); if (assessment.state !== 'ready' || wave.assessment_id !== assessment.id || clone.assessment_id !== assessment.id || wave.state !== 'ready' || clone.state !== 'validated') throw fail('Cutover prerequisites are incomplete', 409, 'CUTOVER_NOT_READY'); const targetRef = key(body.targetRef, 'targetRef'); if (clone.target_ref !== targetRef) throw fail('Cutover target differs from validated clone', 409); const approvalHash = checksum(body.approvalHash, 'approvalHash'); const expected = `CUTOVER ${assessment.id} ${targetRef}`; if (body.confirmation !== expected) throw fail(`confirmation must equal ${expected}`, 400, 'CONFIRMATION_REQUIRED'); const steps = ['final_sync','source_shutdown','network_switch','target_boot','post_boot_validation'].map((name, index) => ({ order: index + 1, name, executor: 'approved-external-adapter', state: 'pending', rollbackBoundary: name !== 'post_boot_validation' })); const confirmationHash = hash(body.confirmation); const planHash = hash({ assessmentHash: assessment.assessment_hash, wavePlanHash: wave.plan_hash, testCloneEvidenceHash: clone.evidence_hash, targetRef, approvalHash, confirmationHash, steps }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_cutover_plans (assessment_id,wave_plan_id,test_clone_id,target_ref,approval_hash,confirmation_hash,steps_json,plan_hash,created_by) VALUES (?,?,?,?,?,?,?,?,?)').run(assessment.id, wave.id, clone.id, targetRef, approvalHash, confirmationHash, stable(steps), planHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, targetRef, approvalHash, steps, state: 'ready', planHash, providerMutationsStarted: 0, executeEndpoint: null };
  }
  planRollback(cutoverPlanId, body, actor) {
    this._admin(actor); const cutover = this._row('migration_cutover_plans', cutoverPlanId, 'Cutover plan'); exact(body, 'rollback', ['triggerReason','sourceNetworkRestorable','sourcePowerRestorable','targetCleanupSupported']); const triggerReason = string(body.triggerReason, 'triggerReason', 300); const preconditions = { sourceNetworkRestorable: body.sourceNetworkRestorable === true, sourcePowerRestorable: body.sourcePowerRestorable === true, targetCleanupSupported: body.targetCleanupSupported === true }; const state = Object.values(preconditions).every(Boolean) ? 'ready' : 'blocked'; const steps = ['isolate_target','restore_source_network','power_on_source','validate_source','cleanup_target'].map((name, index) => ({ order: index + 1, name, executor: 'approved-external-adapter', state: 'pending' })); const planHash = hash({ cutoverPlanHash: cutover.plan_hash, triggerReason, preconditions, steps, state }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_rollback_plans (cutover_plan_id,trigger_reason,preconditions_json,steps_json,state,plan_hash,created_by) VALUES (?,?,?,?,?,?,?)').run(cutover.id, triggerReason, stable(preconditions), stable(steps), state, planHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, cutoverPlanId: cutover.id, triggerReason, preconditions, steps, state, planHash, providerMutationsStarted: 0, executeEndpoint: null };
  }
  createEvidenceReport(assessmentId, body, actor) {
    this._admin(actor); const assessment = this._row('migration_factory_assessments', assessmentId, 'Assessment'); exact(body, 'evidenceReport', ['conversionJobIds','cutoverPlanId','rollbackPlanId','timings','tests','approvals']); const conversions = (body.conversionJobIds || []).map(id => this._row('migration_conversion_jobs', id, 'Conversion job')); const cutover = this._row('migration_cutover_plans', body.cutoverPlanId, 'Cutover plan'); const rollback = this._row('migration_rollback_plans', body.rollbackPlanId, 'Rollback plan'); if (cutover.assessment_id !== assessment.id || conversions.some(row => row.assessment_id !== assessment.id) || rollback.cutover_plan_id !== cutover.id) throw fail('Evidence references do not share an assessment', 409); const timings = safeObject(body.timings || {}, 'timings', 32 * 1024); const tests = safeObject(body.tests || {}, 'tests', 64 * 1024); const approvals = safeObject(body.approvals || {}, 'approvals', 32 * 1024); const references = { assessmentHash: assessment.assessment_hash, conversionRequestHashes: conversions.map(row => row.request_hash), cutoverPlanHash: cutover.plan_hash, rollbackPlanHash: rollback.plan_hash }; const reportHash = hash({ references, timings, tests, approvals }); const saved = this._db().prepare('INSERT OR IGNORE INTO migration_evidence_reports (assessment_id,references_json,timings_json,tests_json,approvals_json,report_hash,created_by) VALUES (?,?,?,?,?,?,?)').run(assessment.id, stable(references), stable(timings), stable(tests), stable(approvals), reportHash, actor.id); return { id: Number(saved.lastInsertRowid) || null, assessmentId: assessment.id, references, timings, tests, approvals, reportHash, rawArtifactsStored: false };
  }
  assessLegacyXen(body, actor) {
    this._admin(actor); exact(body, 'legacyXen', ['hostRef','toolstack','version','vms','targetCandidates']); const hostRef = key(body.hostRef, 'hostRef'); const toolstack = choice(body.toolstack, 'toolstack', ['xm','xl','xend','mixed']); const version = string(body.version, 'version', 80); if (!Array.isArray(body.vms) || !body.vms.length || body.vms.length > 5000) throw fail('vms is invalid'); const vms = body.vms.map((vm, index) => { exact(vm, `vms[${index}]`, ['vmRef','configHash','diskFormats','networkRefs','passthroughDevices']); return { vmRef: key(vm.vmRef, 'vmRef'), configHash: checksum(vm.configHash, 'configHash'), diskFormats: (vm.diskFormats || []).map(item => choice(item, 'diskFormat', [...FORMATS])), networkRefs: (vm.networkRefs || []).map(item => key(item, 'networkRef')), passthroughDevices: (vm.passthroughDevices || []).map(item => key(item, 'passthroughDevice')) }; }); if (!Array.isArray(body.targetCandidates) || !body.targetCandidates.length) throw fail('targetCandidates is invalid'); const targetCandidates = body.targetCandidates.map(item => choice(item, 'targetCandidate', ['xcp-ng','xenserver','xapi'])); const blockers = []; if (['xm','xend','mixed'].includes(toolstack)) blockers.push('legacy_xend_or_xm_requires_offline_config_capture'); for (const vm of vms) { if (!vm.diskFormats.length) blockers.push(`${vm.vmRef}:disk_format_missing`); if (vm.passthroughDevices.length) blockers.push(`${vm.vmRef}:passthrough_review`); } const guidedSteps = ['capture_xm_xl_config','checksum_virtual_disks','map_bridges_to_xapi_networks','convert_or_import_disks','create_isolated_test_vm','validate_guest_tools','plan_cutover_and_rollback']; const state = blockers.length ? 'blocked' : 'ready'; const assessmentHash = hash({ hostRef, toolstack, version, vms, blockers, targetCandidates, guidedSteps }); const found = this._db().prepare('SELECT id FROM legacy_xen_migration_assessments WHERE assessment_hash=?').get(assessmentHash); const id = found?.id || Number(this._db().prepare('INSERT INTO legacy_xen_migration_assessments (host_ref,toolstack,version,inventory_json,blockers_json,target_candidates_json,guided_steps_json,state,assessment_hash,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)').run(hostRef, toolstack, version, stable(vms), stable(blockers), stable(targetCandidates), stable(guidedSteps), state, assessmentHash, actor.id).lastInsertRowid); return { id, hostRef, toolstack, version, vms, blockers, targetCandidates, guidedSteps, state, assessmentHash, providerMutationsStarted: 0 };
  }
  overview(actor) {
    this._admin(actor); const db = this._db(); const tables = { assessments: 'migration_factory_assessments', conversions: 'migration_conversion_jobs', networkMappings: 'migration_network_mappings', storageMappings: 'migration_storage_mappings', testClones: 'migration_test_clones', wavePlans: 'migration_wave_plans', cutovers: 'migration_cutover_plans', rollbacks: 'migration_rollback_plans', evidenceReports: 'migration_evidence_reports', legacyXen: 'legacy_xen_migration_assessments' }; const summary = Object.fromEntries(Object.entries(tables).map(([name, table]) => [name, db.prepare(`SELECT COUNT(*) count FROM ${table}`).get().count])); const assessments = db.prepare('SELECT id,source_provider,target_provider,state,assessment_hash,created_at FROM migration_factory_assessments ORDER BY id DESC LIMIT 100').all().map(row => ({ id: row.id, sourceProvider: row.source_provider, targetProvider: row.target_provider, state: row.state, assessmentHash: row.assessment_hash, createdAt: row.created_at })); return { capabilities: { assessmentScanner: true, sandboxedConversionContract: true, networkMapper: true, storageMapper: true, isolatedTestCloneEvidence: true, wavePlanner: true, cutoverOrchestratorPlan: true, rollbackOrchestratorPlan: true, evidenceReport: true, legacyXenAssistant: true }, safety: { providerMutationsStarted: 0, executeEndpoints: [], conversionBinaryExecuted: false, conversionSandbox: SANDBOX_POLICY }, summary, assessments };
  }
}

const service = new MigrationFactoryService(); module.exports = service; module.exports.MigrationFactoryService = MigrationFactoryService; module.exports.MigrationFactoryError = MigrationFactoryError; module.exports.SANDBOX_POLICY = SANDBOX_POLICY;
