'use strict';

const crypto = require('crypto');
const os = require('os');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { getDb } = require('../db');
const { FEATURE_KEY_SET } = require('./provider-sdk/catalog');
const coreVersion = require('../../package.json').version;

const execFileAsync = promisify(execFile);
class ProviderPluginError extends Error {
  constructor(message, status = 400, code = 'PROVIDER_PLUGIN_ERROR', details) {
    super(message); this.name = 'ProviderPluginError'; this.status = status; this.code = code; this.details = details;
  }
}
const fail = (message, status, code, details) => new ProviderPluginError(message, status, code, details);
const PLUGIN_KEY = /^[a-z][a-z0-9-]{1,63}$/; const VERSION = /^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/; const SAFE = /^[a-zA-Z0-9][a-zA-Z0-9_.:/@+ -]{0,299}$/; const SECRET = /password|secret|token|credential|private.?key|authorization|cookie/i;
const API_VERSION = '1.0'; const SCHEMA_VERSION = '1.0';
const PERMISSIONS = Object.freeze({
  'inventory.read': 'read', 'metrics.write': 'write', 'events.write': 'write', 'provider.mutate': 'mutation', 'secrets.resolve': 'secret', 'network.egress': 'network',
});
const METHODS = new Set(['health.check', 'capabilities.describe', 'inventory.normalize.probe']);
const SANDBOX_POLICY = Object.freeze({ processBoundary: 'node-child-process', codeExecution: 'fixed-control-plane-worker', pluginCodeLoaded: false,
  environment: 'empty', filesystem: 'no-plugin-paths-exposed', network: 'no-plugin-endpoint-invoked', memoryLimitMb: 32, timeoutMs: 2000, maxResponseBytes: 16384 });
const WORKER = `'use strict';const crypto=require('crypto');const input=JSON.parse(Buffer.from(process.argv[1],'base64url').toString('utf8'));const allowed=new Set(['health.check','capabilities.describe','inventory.normalize.probe']);if(!allowed.has(input.method)){process.stderr.write('METHOD_DENIED');process.exit(23)}const response={rpcVersion:'1.0',requestId:input.requestId,pluginKey:input.pluginKey,method:input.method,accepted:true,payloadHash:input.payloadHash,capabilityCount:input.capabilityCount,workerPid:process.pid};process.stdout.write(JSON.stringify(response));`;
const parse = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const canonical = value => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value;
const stable = value => JSON.stringify(canonical(value)); const hash = value => crypto.createHash('sha256').update(stable(value)).digest('hex');
const text = (value, key, max = 300) => { const result = String(value ?? '').trim(); if (!result || result.length > max || !SAFE.test(result)) throw fail(`${key} is invalid`); return result; };
const integer = (value, key, min = 0, max = Number.MAX_SAFE_INTEGER) => { const result = Number(value); if (!Number.isSafeInteger(result) || result < min || result > max) throw fail(`${key} is invalid`); return result; };
const number = (value, key, min = 0, max = 1e15) => { const result = Number(value); if (!Number.isFinite(result) || result < min || result > max) throw fail(`${key} is invalid`); return result; };
const time = (value, key) => { const result = new Date(value); if (Number.isNaN(result.getTime())) throw fail(`${key} is invalid`); return result.toISOString(); };
function safeObject(value, field, maxBytes = 64 * 1024) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw fail(`${field} is invalid`); if (Buffer.byteLength(stable(value)) > maxBytes) throw fail(`${field} is too large`, 413); const walk = (node, path) => { if (!node || typeof node !== 'object') return; for (const [key, child] of Object.entries(node)) { if (SECRET.test(key)) throw fail(`${path}.${key} may not contain secrets`, 400, 'SECRET_FIELD'); walk(child, `${path}.${key}`); } }; walk(value, field); return canonical(value); }
function compareVersions(leftValue, rightValue) { const parts = value => { const match = String(value || '').match(/^(\d+)\.(\d+)\.(\d+)/); return match ? match.slice(1).map(Number) : null; }; const left = parts(leftValue); const right = parts(rightValue); if (!left || !right) return null; for (let index = 0; index < 3; index += 1) { if (left[index] !== right[index]) return left[index] > right[index] ? 1 : -1; } return 0; }
function canonicalPayload(manifest) { return Buffer.from(stable(manifest), 'utf8'); }

class ProviderPluginService {
  constructor(dbProvider = getDb) { this._dbProvider = dbProvider; }
  _db() { return this._dbProvider(); }
  _admin(actor) { if (!actor?.id) throw fail('Authentication required', 401); if (actor.role !== 'admin') throw fail('Administrator required', 403); }
  _row(pluginKeyValue) { const pluginKey = String(pluginKeyValue || '').toLowerCase(); const row = this._db().prepare('SELECT * FROM provider_plugin_manifests WHERE plugin_key=?').get(pluginKey); if (!row) throw fail('Provider plugin not found', 404); return row; }
  _validateManifest(input) {
    const manifest = safeObject(input, 'manifest'); const errors = [];
    if (manifest.schemaVersion !== SCHEMA_VERSION) errors.push(`schemaVersion must be ${SCHEMA_VERSION}`); if (!PLUGIN_KEY.test(manifest.pluginKey || '')) errors.push('pluginKey is invalid'); if (!text(manifest.name, 'manifest.name', 120)) errors.push('name is required'); if (!VERSION.test(manifest.version || '')) errors.push('version is invalid'); if (manifest.apiVersion !== API_VERSION) errors.push(`apiVersion must be ${API_VERSION}`); if (!VERSION.test(manifest.minCoreVersion || '')) errors.push('minCoreVersion is invalid'); if (manifest.maxCoreVersion != null && !VERSION.test(manifest.maxCoreVersion)) errors.push('maxCoreVersion is invalid');
    if (manifest.maxCoreVersion && compareVersions(manifest.minCoreVersion, manifest.maxCoreVersion) > 0) errors.push('core version range is invalid'); if (!Array.isArray(manifest.permissions) || manifest.permissions.length > 32 || new Set(manifest.permissions).size !== manifest.permissions.length || manifest.permissions.some(item => !PERMISSIONS[item])) errors.push('permissions are invalid'); if (!Array.isArray(manifest.capabilities) || manifest.capabilities.length > 128 || new Set(manifest.capabilities).size !== manifest.capabilities.length || manifest.capabilities.some(item => !FEATURE_KEY_SET.has(item))) errors.push('capabilities are invalid'); if (manifest.entrypoint?.kind !== 'declarative-rpc' || manifest.entrypoint?.protocol !== 'json-stdio') errors.push('entrypoint must use declarative-rpc/json-stdio'); if (errors.length) throw fail(`Invalid plugin manifest: ${errors.join('; ')}`, 400, 'INVALID_PLUGIN_MANIFEST'); return manifest;
  }
  register(body, actor) {
    this._admin(actor); const manifest = this._validateManifest(body.manifest); const publicKeyPem = String(body.publicKeyPem || '').trim(); const signatureBase64 = String(body.signatureBase64 || '').trim(); if (!publicKeyPem || publicKeyPem.length > 2048 || !signatureBase64 || signatureBase64.length > 256) throw fail('Signature material is invalid'); let key; let signature;
    try { key = crypto.createPublicKey(publicKeyPem); signature = Buffer.from(signatureBase64, 'base64'); } catch { throw fail('Signature material is invalid', 400, 'INVALID_SIGNATURE'); }
    if (key.asymmetricKeyType !== 'ed25519' || signature.length !== 64 || !crypto.verify(null, canonicalPayload(manifest), key, signature)) throw fail('Manifest signature verification failed', 400, 'INVALID_SIGNATURE');
    const manifestHash = hash(manifest); this._db().prepare(`INSERT INTO provider_plugin_manifests (plugin_key,version,api_version,schema_version,min_core_version,max_core_version,manifest_json,permissions_json,capabilities_json,public_key_pem,signature_base64,manifest_hash,signature_state,enabled,created_by)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,0,?) ON CONFLICT(plugin_key) DO UPDATE SET version=excluded.version,api_version=excluded.api_version,schema_version=excluded.schema_version,min_core_version=excluded.min_core_version,max_core_version=excluded.max_core_version,manifest_json=excluded.manifest_json,permissions_json=excluded.permissions_json,capabilities_json=excluded.capabilities_json,public_key_pem=excluded.public_key_pem,signature_base64=excluded.signature_base64,manifest_hash=excluded.manifest_hash,signature_state='verified',enabled=0,created_by=excluded.created_by,updated_at=datetime('now')`).run(manifest.pluginKey, manifest.version, manifest.apiVersion, manifest.schemaVersion, manifest.minCoreVersion, manifest.maxCoreVersion || null, stable(manifest), stable(manifest.permissions), stable(manifest.capabilities), publicKeyPem, signatureBase64, manifestHash, 'verified', actor.id);
    return { pluginKey: manifest.pluginKey, version: manifest.version, manifestHash, signatureState: 'verified', enabled: false, permissions: manifest.permissions.map(permission => ({ key: permission, risk: PERMISSIONS[permission] })), capabilities: manifest.capabilities };
  }
  consent(pluginKeyValue, body, actor) {
    this._admin(actor); const row = this._row(pluginKeyValue); const permissionKey = text(body.permissionKey, 'permissionKey', 80); const permissions = parse(row.permissions_json, []); if (!permissions.includes(permissionKey)) throw fail('Permission is not declared by this manifest', 404); if (body.manifestHash !== row.manifest_hash) throw fail('Consent manifest hash is stale', 409, 'STALE_MANIFEST'); const decision = String(body.decision || 'denied'); if (!['granted','denied'].includes(decision)) throw fail('decision is invalid'); const reason = text(body.reason, 'reason', 300);
    this._db().prepare(`INSERT INTO provider_plugin_consents (plugin_id,manifest_hash,permission_key,decision,reason,decided_by) VALUES (?,?,?,?,?,?)
      ON CONFLICT(plugin_id,manifest_hash,permission_key) DO UPDATE SET decision=excluded.decision,reason=excluded.reason,decided_by=excluded.decided_by,decided_at=datetime('now')`).run(row.id, row.manifest_hash, permissionKey, decision, reason, actor.id);
    return { pluginKey: row.plugin_key, manifestHash: row.manifest_hash, permissionKey, risk: PERMISSIONS[permissionKey], decision, reason };
  }
  compatibility(pluginKeyValue, actor) {
    this._admin(actor); const row = this._row(pluginKeyValue); const manifest = parse(row.manifest_json, {}); const consents = new Map(this._db().prepare('SELECT permission_key,decision FROM provider_plugin_consents WHERE plugin_id=? AND manifest_hash=?').all(row.id, row.manifest_hash).map(item => [item.permission_key, item.decision])); const checks = [];
    const add = (code, state, evidence) => checks.push({ code, state, evidence }); add('SIGNATURE', row.signature_state === 'verified' ? 'pass' : 'fail', { state: row.signature_state }); add('API_VERSION', row.api_version === API_VERSION ? 'pass' : 'fail', { expected: API_VERSION, actual: row.api_version }); add('SCHEMA_VERSION', row.schema_version === SCHEMA_VERSION ? 'pass' : 'fail', { expected: SCHEMA_VERSION, actual: row.schema_version }); const min = compareVersions(coreVersion, row.min_core_version); const max = row.max_core_version ? compareVersions(coreVersion, row.max_core_version) : -1; add('CORE_VERSION', min != null && min >= 0 && (!row.max_core_version || max <= 0) ? 'pass' : 'fail', { coreVersion, minimum: row.min_core_version, maximum: row.max_core_version }); const invalidCapabilities = (manifest.capabilities || []).filter(item => !FEATURE_KEY_SET.has(item)); add('CAPABILITY_SCHEMA', invalidCapabilities.length ? 'fail' : 'pass', { invalid: invalidCapabilities }); const permissionEvidence = (manifest.permissions || []).map(permission => ({ permission, risk: PERMISSIONS[permission], decision: consents.get(permission) || 'missing' })); add('PERMISSION_CONSENT', permissionEvidence.every(item => item.decision === 'granted') ? 'pass' : 'fail', permissionEvidence); const state = checks.every(item => item.state === 'pass') ? 'ready' : 'blocked'; return { pluginKey: row.plugin_key, version: row.version, manifestHash: row.manifest_hash, state, enabled: Boolean(row.enabled), checks, permissionEvidence };
  }
  enable(pluginKeyValue, body, actor) {
    this._admin(actor); const row = this._row(pluginKeyValue); const enabled = body.enabled === true; const compatibility = this.compatibility(row.plugin_key, actor); if (enabled && compatibility.state !== 'ready') throw fail('Plugin compatibility or consent is incomplete', 409, 'PLUGIN_NOT_READY', compatibility.checks); this._db().prepare('UPDATE provider_plugin_manifests SET enabled=?,updated_at=datetime(\'now\') WHERE id=?').run(enabled ? 1 : 0, row.id); return { pluginKey: row.plugin_key, enabled, manifestHash: row.manifest_hash, state: enabled ? 'enabled' : 'disabled' };
  }
  async sandboxProbe(pluginKeyValue, body, actor) {
    this._admin(actor); const row = this._row(pluginKeyValue); const compatibility = this.compatibility(row.plugin_key, actor); if (!row.enabled || compatibility.state !== 'ready') throw fail('Plugin must be compatible, consented and enabled', 409, 'PLUGIN_NOT_READY'); const method = text(body.method, 'method', 80); if (!METHODS.has(method)) throw fail('Sandbox method is not allowed', 403, 'METHOD_DENIED'); const payload = safeObject(body.payload || {}, 'payload', 16 * 1024); const requestHash = hash({ pluginKey: row.plugin_key, manifestHash: row.manifest_hash, method, payload }); const request = { requestId: crypto.randomUUID(), pluginKey: row.plugin_key, method, payloadHash: hash(payload), capabilityCount: parse(row.capabilities_json, []).length }; const started = Date.now(); let status = 'passed'; let response = null; let responseHash = null; let errorCode = null;
    try { const result = await execFileAsync(process.execPath, [`--max-old-space-size=${SANDBOX_POLICY.memoryLimitMb}`, '-e', WORKER, Buffer.from(JSON.stringify(request)).toString('base64url')], { cwd: os.tmpdir(), env: {}, timeout: SANDBOX_POLICY.timeoutMs, maxBuffer: SANDBOX_POLICY.maxResponseBytes, windowsHide: true }); response = JSON.parse(result.stdout); if (response.requestId !== request.requestId || response.payloadHash !== request.payloadHash) throw new Error('RPC_RESPONSE_MISMATCH'); response.outOfProcess = response.workerPid !== process.pid; delete response.workerPid; responseHash = hash(response); } catch (error) { status = error.killed || error.code === 'ETIMEDOUT' ? 'timeout' : 'failed'; errorCode = status === 'timeout' ? 'SANDBOX_TIMEOUT' : String(error.message || error.code || 'SANDBOX_FAILED').slice(0, 100); }
    const durationMs = Date.now() - started; const saved = this._db().prepare(`INSERT INTO provider_plugin_sandbox_runs (plugin_id,method,request_hash,status,duration_ms,response_json,response_hash,error_code,policy_json,created_by)
      VALUES (?,?,?,?,?,?,?,?,?,?)`).run(row.id, method, requestHash, status, durationMs, response ? stable(response) : null, responseHash, errorCode, stable(SANDBOX_POLICY), actor.id); const output = { id: Number(saved.lastInsertRowid), pluginKey: row.plugin_key, method, requestHash, status, durationMs, response, responseHash, errorCode, policy: SANDBOX_POLICY, outOfProcess: response?.outOfProcess ?? null, payloadReturned: false };
    if (status !== 'passed') throw fail('Sandbox probe failed', status === 'timeout' ? 504 : 502, errorCode, output); return output;
  }
  recordHealth(pluginKeyValue, body, actor) {
    this._admin(actor); safeObject(body, 'health', 8 * 1024); const allowed = new Set(['observedAt','latencyMs','requestCount','errorCount','crashCount']); const unexpected = Object.keys(body).filter(key => !allowed.has(key)); if (unexpected.length) throw fail(`Unexpected health fields: ${unexpected.join(', ')}`, 400, 'UNEXPECTED_FIELD'); const row = this._row(pluginKeyValue); const observedAt = time(body.observedAt || new Date(), 'observedAt'); const latencyMs = number(body.latencyMs, 'latencyMs', 0, 1e7); const requestCount = integer(body.requestCount, 'requestCount', 0, 1e9); const errorCount = integer(body.errorCount, 'errorCount', 0, requestCount); const crashCount = integer(body.crashCount, 'crashCount', 0, 1e9); const evidenceHash = hash({ pluginId: row.id, observedAt, latencyMs, requestCount, errorCount, crashCount }); const found = this._db().prepare('SELECT id FROM provider_plugin_health_metrics WHERE evidence_hash=?').get(evidenceHash); const id = found?.id || Number(this._db().prepare('INSERT INTO provider_plugin_health_metrics (plugin_id,observed_at,latency_ms,request_count,error_count,crash_count,evidence_hash,created_by) VALUES (?,?,?,?,?,?,?,?)').run(row.id, observedAt, latencyMs, requestCount, errorCount, crashCount, evidenceHash, actor.id).lastInsertRowid); const errorRate = requestCount ? Number((errorCount / requestCount).toFixed(4)) : 0; return { id, pluginKey: row.plugin_key, observedAt, latencyMs, requestCount, errorCount, errorRate, crashCount, state: crashCount || errorRate >= 0.1 ? 'degraded' : 'healthy', evidenceHash, duplicate: Boolean(found), payloadFieldsStored: [] };
  }
  overview(actor) {
    this._admin(actor); const rows = this._db().prepare('SELECT * FROM provider_plugin_manifests ORDER BY plugin_key').all(); const plugins = rows.map(row => { const compatibility = this.compatibility(row.plugin_key, actor); const latest = this._db().prepare('SELECT * FROM provider_plugin_health_metrics WHERE plugin_id=? ORDER BY datetime(observed_at) DESC,id DESC LIMIT 1').get(row.id); const health = latest ? { observedAt: latest.observed_at, latencyMs: latest.latency_ms, requestCount: latest.request_count, errorCount: latest.error_count, errorRate: latest.request_count ? Number((latest.error_count / latest.request_count).toFixed(4)) : 0, crashCount: latest.crash_count, state: latest.crash_count || latest.request_count && latest.error_count / latest.request_count >= 0.1 ? 'degraded' : 'healthy' } : null; return { pluginKey: row.plugin_key, version: row.version, manifestHash: row.manifest_hash, signatureState: row.signature_state, enabled: Boolean(row.enabled), permissions: parse(row.permissions_json, []).map(key => ({ key, risk: PERMISSIONS[key] })), capabilities: parse(row.capabilities_json, []), compatibility, health }; }); const runs = this._db().prepare('SELECT r.*,m.plugin_key FROM provider_plugin_sandbox_runs r JOIN provider_plugin_manifests m ON m.id=r.plugin_id ORDER BY r.id DESC LIMIT 100').all().map(row => ({ id: row.id, pluginKey: row.plugin_key, method: row.method, requestHash: row.request_hash, status: row.status, durationMs: row.duration_ms, responseHash: row.response_hash, errorCode: row.error_code, policy: parse(row.policy_json, {}), payloadReturned: false })); return { capabilities: { signedManifest: true, outOfProcessSandbox: true, permissionConsent: true, compatibilityChecker: true, healthTelemetry: true }, contract: { apiVersion: API_VERSION, schemaVersion: SCHEMA_VERSION, coreVersion, allowedPermissions: PERMISSIONS, sandboxPolicy: SANDBOX_POLICY }, plugins, runs };
  }
}

const service = new ProviderPluginService(); module.exports = service; module.exports.ProviderPluginService = ProviderPluginService; module.exports.ProviderPluginError = ProviderPluginError; module.exports.canonicalPayload = canonicalPayload; module.exports.PERMISSIONS = PERMISSIONS; module.exports.SANDBOX_POLICY = SANDBOX_POLICY;
