'use strict';

// Add 21 extra guides to the howto_guides table (migration 038 created the table with 25 initial guides)
exports.up = function(db) {
  const guides = [
    // Docker Deep Dives
    { slug: 'docker-networking-deep', title: 'Docker Networking Deep Dive', title_ro: 'Rețele Docker în detaliu', category: 'networking', difficulty: 'intermediate', icon: 'fas fa-project-diagram', summary: 'Understand bridge, host, overlay, macvlan networks and when to use each.', summary_ro: 'Înțelege rețelele bridge, host, overlay, macvlan și când le folosești.' },
    { slug: 'dockerfile-best-practices', title: 'Dockerfile Best Practices', title_ro: 'Bune practici Dockerfile', category: 'compose', difficulty: 'intermediate', icon: 'fas fa-file-code', summary: 'Write efficient Dockerfiles: multi-stage builds, layer caching, .dockerignore, minimal base images.', summary_ro: 'Scrie Dockerfile-uri eficiente: build-uri multi-etapă, cache de layere, .dockerignore, imagini de bază minimale.' },
    { slug: 'docker-logging', title: 'Docker Logging Strategies', title_ro: 'Strategii de logging Docker', category: 'troubleshooting', difficulty: 'intermediate', icon: 'fas fa-file-alt', summary: 'Configure logging drivers (json-file, syslog, fluentd), log rotation, and centralized logging.', summary_ro: 'Configurează drivere de logging, rotația logurilor și logging centralizat.' },
    { slug: 'docker-storage-drivers', title: 'Docker Storage Drivers', title_ro: 'Drivere de stocare Docker', category: 'performance', difficulty: 'advanced', icon: 'fas fa-hdd', summary: 'Understand overlay2, btrfs, zfs storage drivers and their performance characteristics.', summary_ro: 'Înțelege driverele overlay2, btrfs, zfs și caracteristicile lor de performanță.' },
    { slug: 'docker-multi-stage', title: 'Multi-Stage Docker Builds', title_ro: 'Build-uri Docker multi-etapă', category: 'compose', difficulty: 'intermediate', icon: 'fas fa-layer-group', summary: 'Reduce image size by 90% using multi-stage builds with separate build and runtime stages.', summary_ro: 'Reduce dimensiunea imaginii cu 90% folosind build-uri multi-etapă.' },
    { slug: 'docker-secrets', title: 'Managing Secrets in Docker', title_ro: 'Gestionarea secretelor în Docker', category: 'security', difficulty: 'intermediate', icon: 'fas fa-user-secret', summary: 'Use Docker secrets, .env files, and environment variables securely. Never hardcode credentials.', summary_ro: 'Folosește secrete Docker, fișiere .env și variabile de mediu în siguranță.' },
    { slug: 'docker-exec-debug', title: 'Debugging with docker exec', title_ro: 'Depanare cu docker exec', category: 'troubleshooting', difficulty: 'beginner', icon: 'fas fa-bug', summary: 'Use docker exec to inspect running containers: shell access, process listing, file viewing.', summary_ro: 'Folosește docker exec pentru a inspecta containere: acces shell, procese, fișiere.' },
    { slug: 'docker-registry', title: 'Private Docker Registry', title_ro: 'Registru Docker privat', category: 'basics', difficulty: 'intermediate', icon: 'fas fa-warehouse', summary: 'Set up a private Docker registry to store and distribute your own images.', summary_ro: 'Configurează un registru Docker privat pentru a stoca și distribui propriile imagini.' },
    { slug: 'docker-buildx', title: 'Building Multi-Arch Images', title_ro: 'Imagini Docker multi-arhitectură', category: 'compose', difficulty: 'advanced', icon: 'fas fa-microchip', summary: 'Use Docker Buildx to build images for ARM64, AMD64, and other architectures.', summary_ro: 'Folosește Docker Buildx pentru a construi imagini pentru ARM64, AMD64 și alte arhitecturi.' },
    { slug: 'docker-init-systems', title: 'Init Systems in Containers', title_ro: 'Sisteme de init în containere', category: 'basics', difficulty: 'intermediate', icon: 'fas fa-play', summary: 'Why PID 1 matters, zombie processes, and using tini or dumb-init.', summary_ro: 'De ce contează PID 1, procese zombie și utilizarea tini sau dumb-init.' },
    // Docker Swarm
    { slug: 'swarm-basics', title: 'Docker Swarm Basics', title_ro: 'Bazele Docker Swarm', category: 'docker-dash', difficulty: 'beginner', icon: 'fas fa-sitemap', summary: 'Initialize a swarm, add nodes, deploy services, and understand managers vs workers.', summary_ro: 'Inițializează un swarm, adaugă noduri, deploy-ează servicii, manageri vs workeri.' },
    { slug: 'swarm-services', title: 'Swarm Services & Scaling', title_ro: 'Servicii și scalare Swarm', category: 'docker-dash', difficulty: 'intermediate', icon: 'fas fa-expand-arrows-alt', summary: 'Create, update, and scale services. Rolling updates, rollbacks, and placement constraints.', summary_ro: 'Creează, actualizează și scalează servicii. Rolling updates, rollback-uri, placement.' },
    { slug: 'swarm-networking', title: 'Swarm Overlay Networks', title_ro: 'Rețele overlay Swarm', category: 'networking', difficulty: 'intermediate', icon: 'fas fa-cloud', summary: 'Connect services across nodes with encrypted overlay networks and ingress routing.', summary_ro: 'Conectează servicii între noduri cu rețele overlay criptate și routing ingress.' },
    // Security & CIS
    { slug: 'cis-benchmark', title: 'CIS Docker Benchmark Guide', title_ro: 'Ghid CIS Benchmark Docker', category: 'security', difficulty: 'intermediate', icon: 'fas fa-clipboard-check', summary: 'Understand and implement CIS Docker Benchmark recommendations for host and container hardening.', summary_ro: 'Înțelege și implementează recomandările CIS Docker Benchmark pentru securizare.' },
    { slug: 'docker-security-scanning', title: 'Container Security Scanning', title_ro: 'Scanare securitate containere', category: 'security', difficulty: 'beginner', icon: 'fas fa-search', summary: 'Scan images for CVEs with Trivy, Grype, and Docker Scout. Understand severity levels.', summary_ro: 'Scanează imagini pentru CVE-uri cu Trivy, Grype și Docker Scout.' },
    { slug: 'docker-apparmor-seccomp', title: 'AppArmor & Seccomp Profiles', title_ro: 'Profile AppArmor și Seccomp', category: 'security', difficulty: 'advanced', icon: 'fas fa-shield-alt', summary: 'Restrict container syscalls with seccomp and filesystem access with AppArmor profiles.', summary_ro: 'Restricționează syscall-urile și accesul la fișiere cu profile seccomp și AppArmor.' },
    // Linux Server Extras
    { slug: 'linux-rdp-vnc', title: 'Remote Desktop (RDP/VNC) on Linux', title_ro: 'Desktop la distanță (RDP/VNC) pe Linux', category: 'linux', difficulty: 'intermediate', icon: 'fas fa-desktop', summary: 'Set up xrdp or VNC server on Ubuntu/Debian for remote graphical access.', summary_ro: 'Configurează xrdp sau VNC pe Ubuntu/Debian pentru acces grafic la distanță.' },
    { slug: 'linux-samba', title: 'Samba File Sharing on Linux', title_ro: 'Partajare fișiere Samba pe Linux', category: 'linux', difficulty: 'intermediate', icon: 'fas fa-folder-open', summary: 'Share folders from Linux to Windows/Mac using Samba (SMB/CIFS protocol).', summary_ro: 'Partajează foldere din Linux către Windows/Mac folosind Samba (SMB/CIFS).' },
    { slug: 'linux-sftp', title: 'SFTP Server Setup', title_ro: 'Configurare server SFTP', category: 'linux', difficulty: 'beginner', icon: 'fas fa-upload', summary: 'Set up a secure SFTP server for file transfers using OpenSSH.', summary_ro: 'Configurează un server SFTP securizat pentru transfer de fișiere cu OpenSSH.' },
    { slug: 'linux-firewall', title: 'Linux Firewall (UFW/iptables)', title_ro: 'Firewall Linux (UFW/iptables)', category: 'linux', difficulty: 'intermediate', icon: 'fas fa-fire', summary: 'Configure UFW or iptables firewall rules. Understand the Docker/UFW bypass issue.', summary_ro: 'Configurează reguli firewall UFW sau iptables. Problema Docker/UFW bypass.' },
    { slug: 'linux-systemd', title: 'Systemd Service Management', title_ro: 'Gestionarea serviciilor cu Systemd', category: 'linux', difficulty: 'beginner', icon: 'fas fa-cogs', summary: 'Start, stop, enable, disable services. View logs with journalctl. Create custom service units.', summary_ro: 'Pornește, oprește, activează servicii. Loguri cu journalctl. Unități de serviciu custom.' },
  ];

  const insert = db.prepare(`INSERT OR IGNORE INTO howto_guides (slug, title, title_ro, category, difficulty, icon, summary, summary_ro, is_builtin) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)`);
  for (const g of guides) {
    insert.run(g.slug, g.title, g.title_ro, g.category, g.difficulty, g.icon, g.summary, g.summary_ro);
  }
};
