'use strict';

// v8.76.0 — content lifecycle, guest command and migration-control contracts.
const PERMISSIONS = [
  ['content_lifecycle.manage', 'content_lifecycle', 'manage', 'Manage image replication, template versions and promotions'],
  ['vm_guest_commands.manage', 'vm_guest_commands', 'manage', 'Manage VM leases and official guest-agent command plans'],
  ['migration_operations.manage', 'migration_operations', 'manage', 'Manage migration controls, policies, queue decisions and rollback plans'],
];

exports.up = function up(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS image_replication_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,source_artifact_key TEXT NOT NULL,digest_sha256 TEXT NOT NULL,targets_json TEXT NOT NULL,controls_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS managed_template_versions (id INTEGER PRIMARY KEY AUTOINCREMENT,template_key TEXT NOT NULL,version TEXT NOT NULL,digest_sha256 TEXT NOT NULL,owner_ref TEXT NOT NULL,compatibility_json TEXT NOT NULL,notes TEXT NOT NULL,deprecated INTEGER NOT NULL DEFAULT 0 CHECK(deprecated IN (0,1)),replaced_by_version TEXT,version_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(template_key,version));
    CREATE TABLE IF NOT EXISTS template_promotion_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,template_version_id INTEGER NOT NULL REFERENCES managed_template_versions(id),source_stage TEXT NOT NULL,target_stage TEXT NOT NULL,approval_hashes_json TEXT NOT NULL,checks_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS vm_lease_contracts (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,owner_ref TEXT NOT NULL,expires_at TEXT NOT NULL,end_action TEXT NOT NULL CHECK(end_action IN ('stop','delete')),notification_json TEXT NOT NULL,extension_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('active','expired','extension_required')),contract_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS guest_command_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,provider_type TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN ('shutdown','reboot','script')),agent_evidence_json TEXT NOT NULL,command_contract_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS console_protocol_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_type TEXT NOT NULL,protocols_json TEXT NOT NULL,preferred_protocol TEXT NOT NULL,capability_evidence_json TEXT NOT NULL,security_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),profile_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS live_migration_control_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,source_ref TEXT NOT NULL,target_ref TEXT NOT NULL,prechecks_json TEXT NOT NULL,postchecks_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS cold_migration_control_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,source_ref TEXT NOT NULL,target_ref TEXT NOT NULL,downtime_minutes INTEGER NOT NULL,steps_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_migration_control_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,source_storage TEXT NOT NULL,target_storage TEXT NOT NULL,disk_refs_json TEXT NOT NULL,controls_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS cross_pool_migration_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,source_pool TEXT NOT NULL,target_pool TEXT NOT NULL,network_map_json TEXT NOT NULL,storage_map_json TEXT NOT NULL,identity_boundary_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS cross_provider_migration_workflows (id INTEGER PRIMARY KEY AUTOINCREMENT,assessment_id INTEGER NOT NULL,source_provider TEXT NOT NULL,target_provider TEXT NOT NULL,evidence_refs_json TEXT NOT NULL,phases_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),workflow_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS migration_bandwidth_policies (id INTEGER PRIMARY KEY AUTOINCREMENT,fabric_ref TEXT NOT NULL,bandwidth_mbps INTEGER NOT NULL,compression TEXT NOT NULL,traffic_network TEXT NOT NULL,window_json TEXT NOT NULL,policy_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS migration_queue_policies (id INTEGER PRIMARY KEY AUTOINCREMENT,fabric_ref TEXT NOT NULL,max_concurrent INTEGER NOT NULL,per_tenant_cap INTEGER NOT NULL,priority_weights_json TEXT NOT NULL,aging_minutes INTEGER NOT NULL,preview_json TEXT NOT NULL,policy_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS migration_control_decisions (id INTEGER PRIMARY KEY AUTOINCREMENT,operation_ref TEXT NOT NULL,requested_action TEXT NOT NULL CHECK(requested_action IN ('cancel','force_complete')),operation_state TEXT NOT NULL,native_evidence_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),decision_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS migration_stage_rollback_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,operation_ref TEXT NOT NULL,failure_stage TEXT NOT NULL,preconditions_json TEXT NOT NULL,steps_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE INDEX IF NOT EXISTS idx_template_version_key ON managed_template_versions(template_key,created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_vm_lease_resource ON vm_lease_contracts(resource_key,expires_at);
    CREATE INDEX IF NOT EXISTS idx_migration_live_resource ON live_migration_control_plans(resource_key,created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_migration_queue_fabric ON migration_queue_policies(fabric_ref,created_at DESC);
  `);
  const insert = db.prepare('INSERT OR IGNORE INTO governance_permissions (permission_key,resource_type,verb,description) VALUES (?,?,?,?)');
  for (const permission of PERMISSIONS) insert.run(...permission);
};

exports.down = function down() {};
