'use strict';

// v8.78.0 — B082-B100 advanced storage contracts and adapter evidence.
const PERMISSIONS = [
  ['storage_content.manage', 'storage_content', 'manage', 'Manage format conversion, orphan cleanup and object storage contracts'],
  ['storage_policy.manage', 'storage_policy', 'manage', 'Manage storage policy, QoS, tiering and change plans'],
  ['storage_health.manage', 'storage_health', 'manage', 'Manage latency, path and suite-specific storage health evidence'],
];

exports.up = function up(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS storage_format_conversion_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,source_format TEXT NOT NULL,target_format TEXT NOT NULL,input_digest_sha256 TEXT NOT NULL,workflow_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_policy_catalog_observations (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_host_id INTEGER NOT NULL,provider_type TEXT NOT NULL,observed_at TEXT NOT NULL,policies_json TEXT NOT NULL,summary_json TEXT NOT NULL,observation_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_policy_assignment_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,current_policy_key TEXT,target_policy_key TEXT NOT NULL,compatibility_json TEXT NOT NULL,migration_json TEXT NOT NULL,diff_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_latency_heatmaps (id INTEGER PRIMARY KEY AUTOINCREMENT,scope_key TEXT NOT NULL,observed_at TEXT NOT NULL,samples_json TEXT NOT NULL,summary_json TEXT NOT NULL,heatmap_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_path_health_observations (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_host_id INTEGER NOT NULL,observed_at TEXT NOT NULL,paths_json TEXT NOT NULL,summary_json TEXT NOT NULL,observation_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_orphan_cleanup_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,scope_key TEXT NOT NULL,candidates_json TEXT NOT NULL,retention_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,cleanup_started INTEGER NOT NULL DEFAULT 0 CHECK(cleanup_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_qos_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,current_json TEXT NOT NULL,desired_json TEXT NOT NULL,diff_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_tiering_recommendations (id INTEGER PRIMARY KEY AUTOINCREMENT,workload_key TEXT NOT NULL,requirements_json TEXT NOT NULL,candidates_json TEXT NOT NULL,selected_storage_key TEXT,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),recommendation_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS object_storage_registries (id INTEGER PRIMARY KEY AUTOINCREMENT,endpoint_key TEXT NOT NULL UNIQUE,origin TEXT NOT NULL,provider_type TEXT NOT NULL,region TEXT,secret_ref TEXT NOT NULL,capabilities_json TEXT NOT NULL,health_json TEXT NOT NULL,registry_hash TEXT NOT NULL UNIQUE,network_calls_started INTEGER NOT NULL DEFAULT 0 CHECK(network_calls_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_suite_health_observations (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_host_id INTEGER NOT NULL,suite TEXT NOT NULL CHECK(suite IN ('ceph','longhorn','vsan','s2d','aos')),observed_at TEXT NOT NULL,evidence_json TEXT NOT NULL,summary_json TEXT NOT NULL,observation_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS storage_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,scope_key TEXT NOT NULL,change_kind TEXT NOT NULL,current_json TEXT NOT NULL,desired_json TEXT NOT NULL,diff_json TEXT NOT NULL,impact_json TEXT NOT NULL,rollback_json TEXT NOT NULL,downtime_minutes INTEGER NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE INDEX IF NOT EXISTS idx_storage_policy_catalog_host ON storage_policy_catalog_observations(provider_host_id,observed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_storage_latency_scope ON storage_latency_heatmaps(scope_key,observed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_storage_path_host ON storage_path_health_observations(provider_host_id,observed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_storage_suite_host ON storage_suite_health_observations(provider_host_id,suite,observed_at DESC);
  `);
  const insert = db.prepare('INSERT OR IGNORE INTO governance_permissions (permission_key,resource_type,verb,description) VALUES (?,?,?,?)');
  for (const permission of PERMISSIONS) insert.run(...permission);
};

exports.down = function down() {};
