'use strict';

// v8.79.0 — B102-B117 network lifecycle, policy and flow evidence.
const PERMISSIONS = [
  ['network_attachment.manage', 'network_attachment', 'manage', 'Manage guarded VM NIC attachment and detachment plans'],
  ['network_fabric.manage', 'network_fabric', 'manage', 'Manage mapping, segment, tenant network and address lifecycle plans'],
  ['network_security.manage', 'network_security', 'manage', 'Manage security group, distributed firewall and microsegmentation evidence'],
  ['network_flow.ingest', 'network_flow', 'ingest', 'Ingest bounded normalized network flow evidence'],
];

exports.up = function up(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS network_nic_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_key TEXT NOT NULL,action TEXT NOT NULL CHECK(action IN ('attach','detach')),nic_json TEXT NOT NULL,validation_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS network_mapping_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT,profile_key TEXT NOT NULL,version INTEGER NOT NULL,description TEXT NOT NULL,mappings_json TEXT NOT NULL,checks_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),profile_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(profile_key,version));
    CREATE TABLE IF NOT EXISTS network_segment_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,scope_key TEXT NOT NULL,segment_kind TEXT NOT NULL CHECK(segment_kind IN ('vlan','trunk','qinq','vxlan')),spec_json TEXT NOT NULL,checks_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS tenant_network_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_key TEXT NOT NULL,network_key TEXT NOT NULL,action TEXT NOT NULL CHECK(action IN ('create','update','delete')),current_json TEXT,desired_json TEXT,expected_version TEXT,impact_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS network_address_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,domain TEXT NOT NULL CHECK(domain IN ('ipam','dhcp','dns')),backend TEXT NOT NULL,action TEXT NOT NULL,resource_key TEXT NOT NULL,request_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,external_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(external_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS security_group_inventory_observations (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_host_id INTEGER NOT NULL,provider_type TEXT NOT NULL,observed_at TEXT NOT NULL,groups_json TEXT NOT NULL,summary_json TEXT NOT NULL,observation_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS security_group_change_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,group_key TEXT NOT NULL,current_rules_json TEXT NOT NULL,desired_rules_json TEXT NOT NULL,diff_json TEXT NOT NULL,lockout_json TEXT NOT NULL,rollback_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),plan_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS distributed_firewall_observations (id INTEGER PRIMARY KEY AUTOINCREMENT,provider_host_id INTEGER NOT NULL,provider_type TEXT NOT NULL,scope_key TEXT NOT NULL,observed_at TEXT NOT NULL,layers_json TEXT NOT NULL,coverage_json TEXT NOT NULL,summary_json TEXT NOT NULL,observation_hash TEXT NOT NULL UNIQUE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE TABLE IF NOT EXISTS microsegmentation_policy_versions (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_key TEXT NOT NULL,version INTEGER NOT NULL,stage TEXT NOT NULL CHECK(stage IN ('observe','canary','enforce')),policy_json TEXT NOT NULL,checks_json TEXT NOT NULL,blockers_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('ready','blocked')),policy_hash TEXT NOT NULL UNIQUE,provider_mutations_started INTEGER NOT NULL DEFAULT 0 CHECK(provider_mutations_started=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(policy_key,version));
    CREATE TABLE IF NOT EXISTS network_flow_log_batches (id INTEGER PRIMARY KEY AUTOINCREMENT,source TEXT NOT NULL,provider_host_id INTEGER,observed_at TEXT NOT NULL,retention_until TEXT NOT NULL,entries_json TEXT NOT NULL,summary_json TEXT NOT NULL,batch_hash TEXT NOT NULL UNIQUE,raw_payload_stored INTEGER NOT NULL DEFAULT 0 CHECK(raw_payload_stored=0),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE INDEX IF NOT EXISTS idx_network_nic_resource ON network_nic_change_plans(resource_key,created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_security_group_host ON security_group_inventory_observations(provider_host_id,observed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_distributed_firewall_host ON distributed_firewall_observations(provider_host_id,observed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_network_flow_observed ON network_flow_log_batches(observed_at DESC);
  `);
  const insert = db.prepare('INSERT OR IGNORE INTO governance_permissions (permission_key,resource_type,verb,description) VALUES (?,?,?,?)');
  for (const permission of PERMISSIONS) insert.run(...permission);
};

exports.down = function down() {};
