'use strict';

const Database=require('better-sqlite3');
const fs=require('fs');
const path=require('path');
const migration124=require('../db/migrations/124_governance_foundation');
const migration150=require('../db/migrations/150_vm_content_mobility');
const { VmContentMobilityService }=require('../services/vm-content-mobility');

const admin={id:1,username:'admin',role:'admin'};const sha=character=>character.repeat(64);const pass=(name,character='a')=>({name,state:'pass',evidenceHash:sha(character)});
function database(){const db=new Database(':memory:');db.pragma('foreign_keys = ON');db.exec(`
CREATE TABLE users (id INTEGER PRIMARY KEY,username TEXT UNIQUE,email TEXT,password_hash TEXT,role TEXT,is_active INTEGER DEFAULT 1,display_name TEXT,auth_source TEXT DEFAULT 'local',must_change_password INTEGER DEFAULT 0,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE tenants (id INTEGER PRIMARY KEY,slug TEXT UNIQUE,name TEXT,kind TEXT DEFAULT 'internal',usage_mode TEXT DEFAULT 'production',status TEXT DEFAULT 'active',is_default INTEGER DEFAULT 0,trial_expires_at TEXT,created_by TEXT,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE user_tenants (user_id INTEGER,tenant_id INTEGER,role TEXT,is_owner INTEGER,created_at TEXT,PRIMARY KEY(user_id,tenant_id));
CREATE TABLE teams (id INTEGER PRIMARY KEY,name TEXT UNIQUE,description TEXT,created_by INTEGER,created_at TEXT,updated_at TEXT);CREATE TABLE team_members (team_id INTEGER,user_id INTEGER,is_leader INTEGER,added_by INTEGER,added_at TEXT,PRIMARY KEY(team_id,user_id));
INSERT INTO users (id,username,email,password_hash,role) VALUES (1,'admin','admin@test','x','admin');INSERT INTO tenants (id,slug,name) VALUES (1,'platform','Platform');`);migration124.up(db);migration150.up(db);return db;}
function baseMigration(mode='live'){return{resourceKey:'vm:db1',sourceRef:'host:a',targetRef:'host:b',vmState:mode==='live'?'running':'stopped',capabilitySupported:true,prechecks:[pass('compatibility')],postchecks:['placement','power_state']};}

describe('v8.76 VM content and mobility controls',()=>{let db;let service;beforeEach(()=>{db=database();service=new VmContentMobilityService(()=>db);});afterEach(()=>db.close());
test('B041 plans digest-verified image replication with progress controls',()=>{const plan=service.planImageReplication({sourceArtifactKey:'image:ubuntu',digestSha256:sha('a'),targets:[{siteRef:'site:dc2',clusterRef:'cluster:b',availableBytes:1000,requiredBytes:500,formatSupported:true}],maxConcurrent:2,verifyAfterCopy:true},admin);expect(plan).toMatchObject({state:'ready',controls:{maxConcurrent:2,verifyAfterCopy:true,progressContract:'bytes_and_digest'},providerMutationsStarted:0,executeEndpoint:null});});
test('B042 keeps semantic template versions immutable with ownership and compatibility',()=>{const body={templateKey:'ubuntu.web',version:'1.2.0',digestSha256:sha('b'),ownerRef:'team:platform',compatibility:['proxmox-8','vsphere-8'],notes:'Guest tools current',deprecated:false,replacedByVersion:null};const first=service.saveTemplateVersion(body,admin);expect(first).toMatchObject({version:'1.2.0',ownerRef:'team:platform',duplicate:false});expect(()=>service.saveTemplateVersion({...body,notes:'changed'},admin)).toThrow(expect.objectContaining({code:'IMMUTABLE_VERSION'}));});
test('B043 promotes immutable digests one stage at a time with production approvals',()=>{const template=service.saveTemplateVersion({templateKey:'ubuntu.web',version:'1.2.0',digestSha256:sha('b'),ownerRef:'team:platform',compatibility:[],notes:'Ready',deprecated:false,replacedByVersion:null},admin);const plan=service.planTemplatePromotion(template.id,{sourceStage:'test',targetStage:'prod',approvalHashes:[sha('c'),sha('d')],checks:[pass('boot','e'),pass('security','f')]},admin);expect(plan).toMatchObject({state:'ready',digestSha256:sha('b'),providerMutationsStarted:0,executeEndpoint:null});});
test('B044 creates owner-notified VM TTL contracts with bounded extensions',()=>{const lease=service.createVmLease({resourceKey:'vm:lab1',ownerRef:'user:alice',expiresAt:'2099-01-01T00:00:00Z',endAction:'stop',notifyBeforeMinutes:1440,notificationChannelRef:'email:ops',maxExtensions:2,extensionMinutes:10080,extensionsUsed:0},admin);expect(lease).toMatchObject({state:'active',endAction:'stop',extension:{maxExtensions:2},providerMutationsStarted:0});});
test('B047 gates graceful commands on the official healthy guest agent and digest-only scripts',()=>{const plan=service.planGuestCommand({resourceKey:'vm:db1',providerType:'vsphere',operation:'script',agentEvidence:{installed:true,official:true,healthy:true,version:'13.0.0',supportedOperations:['shutdown','reboot','script']},scriptRef:'runbook:rotate-logs',scriptDigest:sha('a'),args:['--safe'],timeoutSeconds:300},admin);expect(plan).toMatchObject({state:'ready',commandContract:{scriptRef:'runbook:rotate-logs',scriptDigest:sha('a')},providerMutationsStarted:0});expect(()=>service.planGuestCommand({...plan,script:'echo unsafe'},admin)).toThrow();});
test('B049 models noVNC, SPICE handoff, WebMKS and serial behind the protected gateway',()=>{const profile=service.saveConsoleProfile({providerType:'vsphere',protocols:[{protocol:'webmks',transport:'websocket_proxy',supported:true},{protocol:'spice',transport:'native_handoff',supported:true},{protocol:'serial',transport:'ssh_proxy',supported:false}],preferredProtocol:'webmks',capabilityEvidence:[pass('ticket')],tokenTtlSeconds:45,clipboardEnabled:false,fileTransferEnabled:false,auditRequired:true},admin);expect(profile).toMatchObject({state:'ready',security:{singleUse:true,tokenTtlSeconds:45},sessionGateway:'existing-protected-console-gateway'});});
test('B053 binds live migration to running-state pre/post checks and the durable executor',()=>{const plan=service.planLiveMigration(baseMigration('live'),admin);expect(plan).toMatchObject({state:'ready',submissionContract:'existing-durable-vm.migrate',providerMutationsStarted:0});});
test('B054 estimates cold downtime and requires a stopped, gracefully handled VM',()=>{const plan=service.planColdMigration({...baseMigration('cold'),downtimeMinutes:30,guestShutdownSupported:true},admin);expect(plan).toMatchObject({state:'ready',downtimeMinutes:30,steps:['preflight','confirm_vm_stopped','relocate','verify_placement','operator_controlled_start']});});
test('B055 capacity-gates live storage relocation with disk and post-validation evidence',()=>{const plan=service.planStorageMigration({resourceKey:'vm:db1',sourceStorage:'store:a',targetStorage:'store:b',vmState:'running',liveStorageSupported:true,requiredBytes:500,availableBytes:1000,diskRefs:['disk:1'],prechecks:[pass('multipath')],postchecks:['latency','attachment']},admin);expect(plan).toMatchObject({state:'ready',controls:{requiredBytes:500,availableBytes:1000,liveStorageSupported:true},providerMutationsStarted:0});});
test('B056 validates cross-pool network/storage maps and identity boundary without credentials',()=>{const plan=service.planCrossPool({resourceKey:'vm:db1',sourcePool:'pool:a',targetPool:'pool:b',networkMap:[{source:'net:prod',target:'net:prod2',validated:true}],storageMap:[{source:'store:a',target:'store:b',validated:true}],identityBoundary:{sourceScope:'realm:a',targetScope:'realm:b',sameControlPlane:false,brokerApproved:true}},admin);expect(plan).toMatchObject({state:'ready',identityBoundary:{credentialsStored:false},providerMutationsStarted:0,executeEndpoint:null});});
test('B057 links export/convert/import/test/cutover/rollback evidence into a cross-provider workflow',()=>{const workflow=service.planCrossProvider({assessmentId:1,sourceProvider:'vsphere',targetProvider:'proxmox',assessmentHash:sha('a'),conversionHashes:[sha('b')],networkPlanHash:sha('c'),storagePlanHash:sha('d'),testCloneHash:sha('e'),cutoverPlanHash:sha('f'),rollbackPlanHash:sha('1')},admin);expect(workflow).toMatchObject({state:'ready',phases:['export','convert','import','isolated_test','approval','cutover','post_validate','rollback_window'],providerMutationsStarted:0,executeEndpoint:null});});
test('B058 stores throttle, compression, traffic-network and maintenance-window policy',()=>{const policy=service.saveBandwidthPolicy({fabricRef:'fabric:dc1',bandwidthMbps:500,compression:'zstd',trafficNetwork:'net:migration',window:{timezone:'Europe/Bucharest',days:['sat','sun'],start:'22:00',end:'06:00'}},admin);expect(policy).toMatchObject({bandwidthMbps:500,compression:'zstd',trafficNetwork:'net:migration',providerMutationsStarted:0});});
test('B059 previews weighted fair scheduling with per-tenant concurrency caps and aging',()=>{const policy=service.saveQueuePolicy({fabricRef:'fabric:dc1',maxConcurrent:2,perTenantCap:1,priorityWeights:{low:1,normal:10,high:50,critical:100},agingMinutes:30,jobs:[{jobRef:'job:a1',tenantRef:'tenant:a',priority:'critical',waitMinutes:0},{jobRef:'job:a2',tenantRef:'tenant:a',priority:'high',waitMinutes:120},{jobRef:'job:b1',tenantRef:'tenant:b',priority:'normal',waitMinutes:0}]},admin);expect(policy.preview.selected.map(item=>item.jobRef)).toEqual(['job:a1','job:b1']);expect(policy.preview.algorithm).toBe('weighted-fair-aging');});
test('B060 gates cancel/force-complete decisions on provider and observed native state',()=>{const cancel=service.planControlDecision({operationRef:'op:123',requestedAction:'cancel',operationState:'running',providerCancelable:true,providerForceComplete:false,nativeTaskState:'running',nativeEvidenceHash:sha('a'),placementVerified:false},admin);expect(cancel).toMatchObject({state:'ready',executor:'existing-provider-operation-cancel',providerMutationsStarted:0});const forced=service.planControlDecision({operationRef:'op:124',requestedAction:'force_complete',operationState:'unknown',providerCancelable:false,providerForceComplete:true,nativeTaskState:'success',nativeEvidenceHash:sha('b'),placementVerified:false},admin);expect(forced).toMatchObject({state:'blocked',blockers:['force_complete_evidence_insufficient']});});
test('B061 builds stage-aware compensated rollback steps without executing them',()=>{const plan=service.planStageRollback({operationRef:'op:123',failureStage:'post_validation',sourceAvailable:true,sourcePowerRestorable:true,networkReversible:true,storageReversible:true,targetCleanupSupported:true},admin);expect(plan).toMatchObject({state:'ready',steps:['pause_operation','capture_native_evidence','isolate_target','restore_source_storage','restore_source_network','restore_source_power','validate_source','retain_evidence'],providerMutationsStarted:0,executeEndpoint:null});const routes=fs.readFileSync(path.join(__dirname,'..','routes','vm-content-mobility.js'),'utf8');expect(routes).not.toMatch(/router\.(?:post|put)\([^\n]*(?:execute|apply|start-migration)/i);});
test('migration 150 creates fifteen ledgers and three permissions',()=>{const names=['image_replication_plans','managed_template_versions','template_promotion_plans','vm_lease_contracts','guest_command_plans','console_protocol_profiles','live_migration_control_plans','cold_migration_control_plans','storage_migration_control_plans','cross_pool_migration_plans','cross_provider_migration_workflows','migration_bandwidth_policies','migration_queue_policies','migration_control_decisions','migration_stage_rollback_plans'];const tables=db.prepare('SELECT COUNT(*) count FROM sqlite_master WHERE sqlite_master.type=? AND name IN ('+names.map(()=>'?').join(',')+')').get('table',...names).count;const permissions=db.prepare("SELECT COUNT(*) count FROM governance_permissions WHERE permission_key IN ('content_lifecycle.manage','vm_guest_commands.manage','migration_operations.manage')").get().count;expect({tables,permissions}).toEqual({tables:15,permissions:3});});
});
